"""Ownership: the marker, at its canonical position.

`renders.md` § Common rules puts the marker at the file's **first comment**,
preceded only by a prologue the format requires, and names the two: YAML
frontmatter in a markdown output that carries it, and the
`yaml-language-server` schema line at the top of `.coderabbit.yaml`. That set
is cited rather than restated — `_after_prologue` below keys on the extension,
so a second copy of the file list here would go stale against both.

**Ownership is the marker at that position, not the marker anywhere.** A
hand-written file at a generated path that merely quotes or preserves the
marker further down would otherwise read as managed, and `render` would
overwrite bytes `adopt` never took over. `render`, `adopt` and `orphan` all
ask this one question of every output.

**One predicate, whatever the comment syntax**: the marker token is on the
FIRST LINE of the first comment. Every generated marker puts it there — the
HTML form is one line by spec, and the `#` form opens with the token and
closes on its second line — so the rule is one sentence for both, and a new
carrier in a third comment syntax inherits it rather than growing a variant of
it.
"""

from .constants import CODERABBIT_SCHEMA_LINE, MARKER_TOKEN

MARKER_CLOSE_DELIM = "-->"

HTML = "html"
HASH = "hash"


def style_for(path):
    if path.endswith((".yaml", ".yml")):
        return HASH
    if path.endswith(".toml"):
        return HASH
    return HTML


def _after_prologue(path, text):
    """The bytes the marker must open, with the format's prologue removed."""
    if path.endswith(".md") and text.startswith("---\n"):
        end = text.find("\n---\n", 3)
        if end != -1:
            return text[end + 5:]
    if path.endswith((".yaml", ".yml")):
        first = text.split("\n", 1)
        if first[0].strip() == CODERABBIT_SCHEMA_LINE and len(first) > 1:
            return first[1]
    return text


def at_canonical_position(path, text):
    """Does this package own `text` at `path`?"""
    if text is None:
        return False
    opening = _first_comment_line(_after_prologue(path, text), style_for(path))
    return opening is not None and MARKER_TOKEN in opening


def _first_comment_line(body, style):
    """The first line of the body's first comment, and nothing else.

    `None` when the body opens with something that is not a comment, and when
    an HTML comment opens on that line and does not close on it.

    Reading further than this one line is how three overwrites of a file
    `adopt` never took over got in, one per way of reading further. Past the
    `-->`: `<!-- Hand-written. --> generated by bot-instructions.` is a repo's
    own comment with the token outside it. Past an unterminated `<!--`: the
    rest of the file becomes the comment, so a token anywhere below confers
    ownership. Past the first `#` line: a hand-written `.pr_agent.toml` or
    `.coderabbit.yaml` opening with its own header and quoting the token on a
    later header line reads as generated. The three are one cause, so they get
    one rule rather than one branch each.
    """
    for raw in body.split("\n"):
        if not raw.strip():
            continue
        line = raw.lstrip()
        if style == HASH:
            # A `#` comment runs to end of line, so its first line is the line.
            return line if line.startswith("#") else None
        if not line.startswith("<!--"):
            return None
        end = line.find(MARKER_CLOSE_DELIM)
        return line[: end + len(MARKER_CLOSE_DELIM)] if end != -1 else None
    return None


def region_owned(region_body):
    """The `AGENTS.md` owned region, whose marker opens the region's body."""
    return at_canonical_position("AGENTS.md", region_body or "")


def insert(path, text, marker_text):
    """Put the marker at the canonical position of an existing file."""
    if path.endswith(".md") and text.startswith("---\n"):
        end = text.find("\n---\n", 3)
        if end != -1:
            return text[: end + 5] + "\n" + marker_text + "\n" + text[end + 5:]
    if path.endswith((".yaml", ".yml")):
        head, _, rest = text.partition("\n")
        if head.strip() == CODERABBIT_SCHEMA_LINE:
            return head + "\n" + marker_text + "\n" + rest
    return marker_text + "\n\n" + text
