"""Ownership: the marker this package writes, matched exactly.

`renders.md` § Common rules puts the marker at the file's **first comment**,
preceded only by a prologue the format requires, and names exactly two
prologues: YAML frontmatter in the markdown outputs that carry it, and the
`yaml-language-server` schema line at the top of `.coderabbit.yaml`.

**Ownership is that the first line IS the marker.** Byte for byte, with the
version and the recorded input paths the only fields left free, and free only
inside the classes `spec.py` refuses outside of. `render`, `adopt` and
`orphan` all ask that one question of every output.

An exact match rather than a search for the marker token, because a search is
what three rounds of string tests each let a hand-written file through: a
token after a closed comment, a token below a comment that never closed, a
token on a later line of a `#` run, and — the shape that ends the argument —
a first line reading `# not generated by bot-instructions`, a disclaimer that
every containment test reads as a claim. An exact match cannot be satisfied by
a quotation, by a denial, or by a sentence that merely holds the words.

**Two questions, not one.** The marker line is the same for both, and only
what may precede it differs:

- `at_canonical_position` is the WRITE question — *is this the file we wrote
  AT this path?* Strict about both things a path decides: only the prologue
  `renders.md` gives this path may precede the marker, and only that format's
  comment syntax may carry it. `render`, `adopt` and `insert` ask it, because
  they are about to replace bytes. Reading any `---` block as frontmatter let
  a hand-written `REVIEW.md`, `best_practices.md` or `AGENTS.md` region open
  with a frontmatter-shaped block and choose which line was read next.
- `carries_marker` is the READ question — *did we write this, wherever it
  sits now?* Generous about both, because the path is where the file ENDED UP
  rather than where it was written. `orphan` asks it, and a MOVED file is its
  case rather than an exotic one: a rendered
  `.macroscope/correctness/<surface>.md` copied to
  `.macroscope/approvability.md` keeps its frontmatter, and judging it by the
  destination's prologue rule blinded the validator in the situation it
  exists for.

Generosity is safe on the read side and only there. The line still has to BE
the marker, byte for byte, so nothing but a copy of this package's own output
satisfies either question; what differs is the cost of being wrong. Too
generous on the write side loses a file. Too strict on the read side loses a
report about a file that is still live.

`prologue_for` is `renders.md`'s set keyed by path, `_split_prologue` takes
off whichever prologues its caller allows, and `insert` writes through the
same tuple the write question reads with — so where the marker goes and where
it is looked for cannot drift apart.
"""

import re

from .constants import (
    CODERABBIT_SCHEMA_LINE,
    MARKER_CLOSE,
    MARKER_PATH_CLASS,
    MARKER_TOKEN,
    MARKER_VERSION_CLASS,
)

HTML = "html"
HASH = "hash"

FRONTMATTER = "frontmatter"
SCHEMA_LINE = "schema-line"

# `renders.md` § Common rules names the two prologues by the outputs that
# carry them: `.coderabbit.yaml` takes the schema line, and frontmatter
# belongs to `.instructions.md` and `.macroscope/correctness/<surface>.md`.
# `doctrine.md` is the one file in that tree the render gives no frontmatter,
# so it is not in the set.
SCHEMA_LINE_PATH = ".coderabbit.yaml"
CORRECTNESS_TREE = ".macroscope/correctness/"
CORRECTNESS_DOCTRINE = CORRECTNESS_TREE + "doctrine.md"

# The two free fields, built from the classes `spec.py` refuses outside of —
# which is what makes every other character of the marker line a constant this
# can match exactly.
_VERSION = f"[{MARKER_VERSION_CLASS}]+"
_PATHS = f"[{MARKER_PATH_CLASS}]+(?:, [{MARKER_PATH_CLASS}]+)*"


def style_for(path):
    """The comment syntax `path`'s format uses."""
    if path.endswith((".yaml", ".yml", ".toml")):
        return HASH
    return HTML


def comment(style, version, inputs):
    """The marker this package writes. The one statement of its form.

    The HTML form is ONE line: `.macroscope/ignore.md` reads every non-blank
    line as a pattern unless the whole line is a comment, so a marker wrapped
    across two lines would put its second line into that file as a pattern.
    The `#` form opens with the same head and closes on a second line, which
    is why the ownership test reads the first line of either.
    """
    head = f"{MARKER_TOKEN} {version} from {', '.join(inputs)}."
    if style == HTML:
        return f"<!-- {head} {MARKER_CLOSE} -->"
    return f"# {head}\n# {MARKER_CLOSE}"


def _pattern(style):
    """`comment`'s first line as a pattern, its two free fields left open.

    Built by running the emitter over sentinels and escaping what comes back,
    so the form is written once. A pattern spelled out by hand beside the
    emitter is two statements of one string, and the reader and the writer of
    a string stated twice are what this module has spent three rounds fixing.
    """
    version, paths = "ZZVERSIONZZ", "ZZPATHSZZ"
    first = comment(style, version, [paths]).split("\n")[0]
    body = re.escape(first).replace(version, _VERSION).replace(paths, _PATHS)
    return re.compile("^" + body + "$")


_FIRST_LINE = {HTML: _pattern(HTML), HASH: _pattern(HASH)}

# What the READ question allows: every prologue and every comment syntax this
# package writes, since a moved file kept the ones its ORIGINAL path gave it.
PROLOGUES = (FRONTMATTER, SCHEMA_LINE)
STYLES = tuple(_FIRST_LINE)


def prologue_for(path):
    """Which prologue `path`'s format puts above the marker, or None."""
    if path == SCHEMA_LINE_PATH:
        return SCHEMA_LINE
    if path.endswith(".instructions.md"):
        return FRONTMATTER
    if (path.startswith(CORRECTNESS_TREE) and path.endswith(".md")
            and path != CORRECTNESS_DOCTRINE):
        return FRONTMATTER
    return None


def _split_prologue(text, kinds):
    """`(prologue, body)`: the prologue `text` opens with, and what follows it.

    `kinds` is what the caller will allow — one path's own prologue for the
    write question, every prologue this package writes for the read one — so
    the two differ by that tuple and by nothing else. Text that does not open
    with an allowed prologue gets `("", text)`, and the marker then has to be
    the first thing in it.
    """
    if FRONTMATTER in kinds and text.startswith("---\n"):
        end = text.find("\n---\n", 3)
        if end != -1:
            return text[: end + 5], text[end + 5:]
    if SCHEMA_LINE in kinds:
        head, sep, rest = text.partition("\n")
        if sep and head.strip() == CODERABBIT_SCHEMA_LINE:
            return head + sep, rest
    return "", text


def _opens_with_marker(body, styles):
    """Is the first non-blank line of `body` the marker, in one of `styles`?"""
    for line in body.split("\n"):
        if not line.strip():
            continue
        return any(_FIRST_LINE[style].match(line) for style in styles)
    return False


def at_canonical_position(path, text):
    """The WRITE question: is `text` the file this package wrote AT `path`?

    Strict on both axes the path decides. Everything about to replace bytes
    asks this one.
    """
    if text is None:
        return False
    _, body = _split_prologue(text, (prologue_for(path),))
    return _opens_with_marker(body, (style_for(path),))


def carries_marker(path, text):
    """The READ question: did this package write `text`, wherever it sits now?

    Generous on both axes, because a file that was moved answers the write
    question at a path it was never written for. `orphan` asks this one.
    """
    if text is None:
        return False
    _, body = _split_prologue(text, PROLOGUES)
    return _opens_with_marker(body, STYLES)


def region_owned(region_body):
    """The `AGENTS.md` owned region, whose marker opens the region's body.

    The write question, because a region is never a whole file: it cannot be
    moved to another path, so there is no moved copy for the read question to
    find, and every caller here is either splicing the region or taking it
    over.
    """
    return at_canonical_position("AGENTS.md", region_body or "")


def insert(path, text, marker_text):
    """Put the marker where the WRITE question looks for it.

    The same `(prologue_for(path),)` that question reads with, so a file this
    writes is a file it then recognises.

    The gap under a prologue is what the renderer writes there: a blank line
    under frontmatter, and none under the schema line, which is itself a `#`
    comment the marker follows directly. `adopt` producing a different shape
    from `render` would show as a diff on the next render of a file nobody
    edited.
    """
    kind = prologue_for(path)
    prologue, body = _split_prologue(text, (kind,))
    if not prologue:
        return marker_text + "\n\n" + text
    gap = "\n" if kind == FRONTMATTER else ""
    return prologue + gap + marker_text + "\n" + body
