// Generated by pi-extensions/pi-root-policy.mjs; do not edit.
import { homedir } from "node:os";
import { posix, win32 } from "node:path";

function isAbsolute(value, platform) {
	if (platform === "posix") return value.startsWith("/");
	if (/^[A-Za-z]:[\\/]/.test(value)) return true;
	return /^(?:\\\\|\/\/)[^\\/]+[\\/][^\\/]+(?:[\\/]|$)/.test(value);
}

export function piGlobalRoot(
	value = process.env.PI_CODING_AGENT_DIR,
	home = homedir(),
	platform = process.platform === "win32" ? "win32" : "posix",
) {
	const paths = platform === "win32" ? win32 : posix;
	const configured = value?.trim();
	if (!configured) return paths.resolve(home, ".pi", "agent");
	const expanded = configured === "~" ? home : configured.startsWith("~/") ? paths.join(home, configured.slice(2)) : configured;
	return isAbsolute(expanded, platform) ? paths.resolve(expanded) : paths.resolve(home, ".pi", "agent");
}
