// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	scanMachine: () => typedError<ScanResult, string>(__TAURI_INVOKE("scan_machine")),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	updateSettings: (settings: AppSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("update_settings", { settings })),
	/**
	 *  The size on screen, written on its own. Nothing else in the file moves
	 *  with it, and nothing else can move it: a size the person is looking at
	 *  survives whatever else is being saved at the same moment.
	 */
	saveZoom: (percent: number) => typedError<number, string>(__TAURI_INVOKE("save_zoom", { percent })),
	registerProject: (path: string) => typedError<AppSettings, string>(__TAURI_INVOKE("register_project", { path })),
	unregisterProject: (path: string) => typedError<AppSettings, string>(__TAURI_INVOKE("unregister_project", { path })),
	/**
	 *  Install the session-start drift report hook for a scope: script into the
	 *  scope's local source, declaration into its manifest, then the ordinary
	 *  apply renders it. The offer surface (project registration) calls this
	 *  after the user says yes — the declared, user-approved install per scope.
	 *  Returns whether the hook was fully rendered. The user approved the hook
	 *  and nothing else, so the rendering apply runs only when the scope had no
	 *  other pending work; otherwise the declaration lands and `false` says the
	 *  Review page's ordinary preview-and-apply finishes the job.
	 */
	installDriftHook: (scope: Scope) => typedError<boolean, string>(__TAURI_INVOKE("install_drift_hook", { scope })),
	discoverProjects: (root: string) => typedError<string[], string>(__TAURI_INVOKE("discover_projects", { root })),
	/**
	 *  The full harness × kind capability matrix — the UI gates every action on
	 *  this, never on its own assumptions.
	 */
	capabilityTable: () => __TAURI_INVOKE<CapabilityRow[]>("capability_table"),
	/**
	 *  Where a problem report about this item belongs: the kendex upstream
	 *  (with a prefilled issue link) or the user's own repo.
	 */
	reportRoute: (scope: Scope, name: string, kind: "agent" | "skill" | "hook" | "command" | "mcp-server" | "plugin" | "pi-extension" | null) => typedError<ReportRouteView, string>(__TAURI_INVOKE("report_route", { scope, name, kind })),
	auditAll: () => typedError<AuditView_Serialize[], string>(__TAURI_INVOKE("audit_all")),
	applyPlan: (scope: Scope, removeOrphans: boolean, allowUnsafe: string[]) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("apply_plan", { scope, removeOrphans, allowUnsafe })),
	adoptItem: (scope: Scope, kind: ItemKind, name: string, harness: HarnessId) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("adopt_item", { scope, kind, name, harness })),
	replaceUnmanagedItem: (scope: Scope, kind: ItemKind, name: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("replace_unmanaged_item", { scope, kind, name })),
	toggleItem: (scope: Scope, kind: ItemKind, name: string, enabled: boolean) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("toggle_item", { scope, kind, name, enabled })),
	removeItem: (scope: Scope, kind: ItemKind, name: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("remove_item", { scope, kind, name })),
	/**
	 *  Every recorded decision across every scope, each read against what is
	 *  installed there now.
	 */
	listDecisions: () => typedError<DecisionsView_Serialize, string>(__TAURI_INVOKE("list_decisions")),
	/**
	 *  Dismiss the findings these tokens name, for one reason, in one scope.
	 *  The tokens are re-read against a fresh audit before anything is written;
	 *  one that no longer names what is installed stops the whole call.
	 */
	dismissFindings: (scope: Scope, tokens: string[], reason: DismissReason) => typedError<Dismissed_Serialize, string>(__TAURI_INVOKE("dismiss_findings", { scope, tokens, reason })),
	/**
	 *  Take a dismissal back. `dismissed_at` pins the exact record: a stale undo
	 *  finding a newer dismissal at the same key refuses rather than deleting
	 *  somebody's later decision.
	 */
	revokeDismissal: (scope: Scope, key: string, fingerprint: string, dismissedAt: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("revoke_dismissal", { scope, key, fingerprint, dismissedAt })),
	revokeSafetyOverride: (scope: Scope, key: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("revoke_safety_override", { scope, key })),
	getManifest: (scope: Scope) => typedError<{
	schema: number,
	sources?: { [key in string]: SourceDecl_Serialize },
	install: InstallDefaults,
	agents?: { [key in string]: ItemDecl_Serialize },
	skills?: { [key in string]: ItemDecl_Serialize },
	hooks?: { [key in string]: ItemDecl_Serialize },
	commands?: { [key in string]: ItemDecl_Serialize },
	"mcp-servers"?: { [key in string]: ItemDecl_Serialize },
	/**
	 *  Plugins are observe + enable/disable only; the key is
	 *  `name@marketplace`, provenance lives in the lock.
	 */
	plugins?: { [key in string]: PluginDecl },
	/**
	 *  Installed bundles: a curated set the catalog offers under one name.
	 *  What the set holds is the catalog's to say and derives on every plan;
	 *  this records only that the set is installed, and how its members
	 *  install — the same choices any declaration makes.
	 */
	bundles?: { [key in string]: ItemDecl_Serialize },
	"pi-extensions"?: { [key in string]: ItemDecl_Serialize },
	/**
	 *  Items the user removed and wants kept removed, by kind: a dependency
	 *  another item requires, or a member of an installed bundle. A refresh
	 *  honors these instead of re-deriving what was taken away, and the item
	 *  that wanted them says so in the audit.
	 */
	suppressed?: Partial<{ [key in ItemKind]: string[] }>,
	/**
	 *  Optional dependencies taken at install time, per item that offers
	 *  them. A choice, so it belongs here and survives refresh, cache loss,
	 *  and other machines; what those choices pull in does not.
	 */
	"optional-dependencies"?: { [key in string]: string[] },
	/**
	 *  Reviews of content the safety gate blocked, keyed by installation.
	 *  Each one binds to the content, the rule set and the findings it was
	 *  granted against, so it stops applying the moment any of them moves.
	 */
	"safety-overrides"?: { [key in string]: SafetyOverride_Serialize },
	/**
	 *  Findings judged not to be problems, keyed by installation, one
	 *  snapshot of the reviewed content per installation with each
	 *  dismissal beneath it. A dismissal settles a question and never
	 *  unblocks anything.
	 */
	"safety-reviews"?: { [key in string]: SafetyReview_Serialize },
	"agent-skills"?: { [key in string]: string[] },
	"agent-launch-instructions"?: { [key in string]: string },
	"agent-additional-instructions"?: { [key in string]: string },
	"skill-instructions"?: { [key in string]: string },
	/**  `[agent-frontmatter.<harness>.<agent>]`. */
	"agent-frontmatter"?: { [key in string]: { [key in string]: FrontmatterOverrides_Serialize } },
	"custom-hooks"?: CustomHook_Serialize[],
	/**
	 *  Forked items by kind and name — `[forks.skill.<name>]`. The name is
	 *  the item's installed name, unchanged by forking.
	 */
	forks?: Partial<{ [key in ItemKind]: { [key in string]: ForkProvenance_Serialize } }>,
} | null, string>(__TAURI_INVOKE("get_manifest", { scope })),
	/**  Write an edited manifest and reconcile the scope to it. */
	updateManifest: (scope: Scope, manifest: Manifest_Deserialize) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("update_manifest", { scope, manifest })),
	editorInventory: (scope: Scope) => typedError<EditorInventory, string>(__TAURI_INVOKE("editor_inventory", { scope })),
	/**
	 *  Per-hook, per-harness delivery for the hooks as currently drafted in the
	 *  editor — outer Vec in the order the hooks were passed.
	 */
	customHookDeliveries: (scope: Scope, hooks: CustomHook_Deserialize[]) => typedError<HookDelivery[][], string>(__TAURI_INVOKE("custom_hook_deliveries", { scope, hooks })),
	/**
	 *  The primary file behind one installed item, for the Library preview
	 *  pane — SKILL.md for a skill, the document itself for everything else
	 *  that has its own file.
	 */
	itemSource: (scope: Scope, kind: ItemKind, name: string, harness: HarnessId) => typedError<ItemSource, string>(__TAURI_INVOKE("item_source", { scope, kind, name, harness })),
	/**
	 *  Native folder picker. Blocking, so this must not run on the main thread
	 *  — an async command already runs off it, which is what the plugin's own
	 *  docs call for.
	 */
	pickFolder: () => typedError<string | null, string>(__TAURI_INVOKE("pick_folder")),
	/**
	 *  Shows `path` in the system file browser. Only ever reveals a path that
	 *  is actually there — the plain-word error is the fix, not a stack trace
	 *  from the OS call that would have failed instead.
	 */
	revealPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_path", { path })),
	/**
	 *  Opens `path` (file or directory — every candidate editor accepts both)
	 *  in the user's code editor. Not routed through `process::Hardened`: that
	 *  constructor hardens tool invocations core makes with captured output
	 *  and a timeout, but this is an app-shell concern with a different shape
	 *  — no shell, nothing to capture, and no timeout, because the editor is
	 *  the user's own long-lived GUI app and is meant to outlive us.
	 */
	openInEditor: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_in_editor", { path })),
	/**
	 *  Opens a web page in the person's browser. https only — the one thing
	 *  this is for is kendex.ai and GitHub pages, and a file: or custom-scheme
	 *  URL through the system opener is an execution vector, not a page.
	 *  Plain http is allowed only when the host is exactly the local machine:
	 *  a prefix check would wave through `http://localhost.evil.example`.
	 */
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	/**  Every declared source in every scope — the Sources page's one query. */
	sourcesOverview: () => typedError<SourceRow[], string>(__TAURI_INVOKE("sources_overview")),
	sourceAdd: (scope: Scope, name: string, reference: string) => typedError<SourceRow[], string>(__TAURI_INVOKE("source_add", { scope, name, reference })),
	sourceRemove: (scope: Scope, name: string) => typedError<SourceRow[], string>(__TAURI_INVOKE("source_remove", { scope, name })),
	sourceToggle: (scope: Scope, name: string, enabled: boolean) => typedError<SourceRow[], string>(__TAURI_INVOKE("source_toggle", { scope, name, enabled })),
	/**
	 *  Re-resolve every enabled remote across every scope. Returns warnings
	 *  (offline caches keep serving); hard failures surface as the error.
	 */
	sourcesRefresh: () => typedError<string[], string>(__TAURI_INVOKE("sources_refresh")),
	/**
	 *  Every curated set every catalog offers, across every scope — what the
	 *  Catalogs page lists under each source.
	 */
	bundlesOverview: () => typedError<BundleRow[], string>(__TAURI_INVOKE("bundles_overview")),
	/**
	 *  Install a set whole. Its members derive from the catalog, so this declares
	 *  one name and applies the plan that follows from it.
	 */
	bundleInstall: (scope: Scope, source: string, name: string, hold: boolean) => typedError<BundleRow[], string>(__TAURI_INVOKE("bundle_install", { scope, source, name, hold })),
	/**
	 *  Every subscription across every scope — the Marketplaces page's one
	 *  query.
	 */
	marketplacesOverview: () => typedError<MarketplaceRow[], string>(__TAURI_INVOKE("marketplaces_overview")),
	/**
	 *  Every package one catalog offers, across kinds, with installed state
	 *  joined in.
	 */
	marketplacePackages: (catalog: Catalog) => typedError<AvailablePackage[], string>(__TAURI_INVOKE("marketplace_packages", { catalog })),
	/**
	 *  What a catalog says about itself, fetched fresh for a repository nobody
	 *  subscribes to — the marketplace page's header, and the subscription to
	 *  carry on as when this machine already holds one.
	 */
	marketplaceSummary: (catalog: Catalog) => typedError<CatalogSummary, string>(__TAURI_INVOKE("marketplace_summary", { catalog })),
	/**  One curated set with per-member installed state. */
	marketplaceBundle: (catalog: Catalog, name: string) => typedError<BundleDetail, string>(__TAURI_INVOKE("marketplace_bundle", { catalog, name })),
	marketplacePackagePreview: (catalog: Catalog, kind: ItemKind, name: string) => typedError<PackageView, string>(__TAURI_INVOKE("marketplace_package_preview", { catalog, kind, name })),
	/**
	 *  One offered file's content before install — the same read an installed
	 *  package's file gets, confined to the package inside the catalog.
	 */
	marketplacePackageFile: (catalog: Catalog, kind: ItemKind, name: string, path: string) => typedError<ItemSource, string>(__TAURI_INVOKE("marketplace_package_file", { catalog, kind, name, path })),
	/**
	 *  Install packages or a curated set from one subscription. `destination`
	 *  redirects the install from the scope being browsed into a project: the
	 *  project gains the personal subscription first (§4.1), then the add runs
	 *  there — every write lands in exactly one scope.
	 */
	marketplaceInstall: (scope: Scope, source: string, items: InstallItem[], bundle: string | null, destination: { scope: "global" } | { scope: "project"; root: string } | null, hold: boolean) => typedError<AvailablePackage[], string>(__TAURI_INVOKE("marketplace_install", { scope, source, items, bundle, destination, hold })),
	/**
	 *  Subscribe a scope to a marketplace: `owner/repo[@rev]`, a git URL, a
	 *  GitHub tree URL, a skills.sh package URL, or a local folder.
	 */
	marketplaceSubscribe: (scope: Scope, reference: string, name: string | null) => typedError<SubscribeOutcome, string>(__TAURI_INVOKE("marketplace_subscribe", { scope, reference, name })),
	/**
	 *  The dialog's preview: the closure partitioned into removable, edited, and
	 *  the bundles that go. Refuses (as an error) while the source cannot be read.
	 */
	marketplaceUnsubscribePreview: (scope: Scope, source: string) => typedError<UnsubscribePreview, string>(__TAURI_INVOKE("marketplace_unsubscribe_preview", { scope, source })),
	/**
	 *  Unsubscribe, removing or keeping the packages. `keep` converts each
	 *  installation to a local fork; otherwise they are uninstalled, and
	 *  `discard_edits` takes hand edits along instead of refusing.
	 */
	marketplaceUnsubscribe: (scope: Scope, source: string, keep: boolean, discardEdits: boolean) => typedError<null, string>(__TAURI_INVOKE("marketplace_unsubscribe", { scope, source, keep, discardEdits })),
	/**
	 *  The directory as the tab shows it. `refresh` forces a revalidation;
	 *  otherwise the cached list is served within its TTL.
	 */
	communityDirectory: (refresh: boolean) => typedError<DirectoryView, string>(__TAURI_INVOKE("community_directory", { refresh })),
	/**
	 *  Search skills.sh directly — public API, no account, only skills.sh
	 *  sees the query.
	 */
	communitySkillsshSearch: (query: string) => typedError<SkillsShHit[], string>(__TAURI_INVOKE("community_skillssh_search", { query })),
	/**
	 *  Trending / Hot / Top through the kendex.ai proxy. An error here means
	 *  "no proxy" — the chips hide, search stays.
	 */
	communitySkillsshLeaderboard: (view: string) => typedError<SkillsShHit[], string>(__TAURI_INVOKE("community_skillssh_leaderboard", { view })),
	/**
	 *  Whether the skills.sh surface is on at all — the tab hides the
	 *  sub-tab when it is not, rather than showing a dead search box.
	 */
	communitySkillsshAvailable: () => typedError<boolean, string>(__TAURI_INVOKE("community_skillssh_available")),
	marketplaceAbout: (catalog: Catalog) => typedError<AboutView, string>(__TAURI_INVOKE("marketplace_about", { catalog })),
	/**
	 *  Where every installation came from, across every scope — the Library
	 *  table's From column in one query.
	 */
	libraryProvenance: () => typedError<ProvenanceRow[], string>(__TAURI_INVOKE("library_provenance")),
	mineList: () => typedError<MineListRow[], string>(__TAURI_INVOKE("mine_list")),
	mineUseExisting: (path: string) => typedError<MineRow, string>(__TAURI_INVOKE("mine_use_existing", { path })),
	mineCreate: (request: CreateRequest) => typedError<MineRow, string>(__TAURI_INVOKE("mine_create", { request })),
	mineForget: (path: string) => typedError<null, string>(__TAURI_INVOKE("mine_forget", { path })),
	mineImportInventory: () => typedError<ImportCandidate[], string>(__TAURI_INVOKE("mine_import_inventory")),
	mineImportApply: (target: string, selections: ImportSelection[]) => typedError<ImportOutcome, string>(__TAURI_INVOKE("mine_import_apply", { target, selections })),
	mineOfferManifest: (path: string, name: string, description: string, authorName: string) => typedError<OfferPreview, string>(__TAURI_INVOKE("mine_offer_manifest", { path, name, description, authorName })),
	mineOfferWorkflow: (path: string) => typedError<OfferPreview, string>(__TAURI_INVOKE("mine_offer_workflow", { path })),
	mineAcceptManifest: (path: string, name: string, description: string, authorName: string) => typedError<MineRow, string>(__TAURI_INVOKE("mine_accept_manifest", { path, name, description, authorName })),
	mineAcceptWorkflow: (path: string) => typedError<MineRow, string>(__TAURI_INVOKE("mine_accept_workflow", { path })),
	/**
	 *  The one authoring document, compiled in so the app renders the same
	 *  text the repository publishes.
	 */
	mineAuthoringDoc: () => __TAURI_INVOKE<string>("mine_authoring_doc"),
	accountStatus: () => typedError<AccountStatus, string>(__TAURI_INVOKE("account_status")),
	accountLoginStart: () => typedError<LoginStart, string>(__TAURI_INVOKE("account_login_start")),
	/**  One poll; the frontend owns the timer so a closed dialog stops asking. */
	accountLoginPoll: (deviceCode: string) => typedError<string, string>(__TAURI_INVOKE("account_login_poll", { deviceCode })),
	accountLogout: () => typedError<null, string>(__TAURI_INVOKE("account_logout")),
	mineSubmitPreflight: (path: string) => typedError<SubmitPreflight, string>(__TAURI_INVOKE("mine_submit_preflight", { path })),
	mineSubmit: (repo: string) => typedError<SubmittedView, string>(__TAURI_INVOKE("mine_submit", { repo })),
	mineSubmissions: () => typedError<SubmissionRow[], string>(__TAURI_INVOKE("mine_submissions")),
	packageVersions: (scope: Scope, kind: ItemKind, name: string) => typedError<VersionRow[], string>(__TAURI_INVOKE("package_versions", { scope, kind, name })),
	/**
	 *  Every scope's update standing in one query — the sidebar badge, the
	 *  Updates page, and the Library's fork/edited flags all read this. Rows
	 *  carry the facts; warnings carry every package the standing could not be
	 *  computed for, which is never silently shown as current.
	 */
	updatesOverview: () => typedError<UpdatesReport_Serialize, string>(__TAURI_INVOKE("updates_overview")),
	/**
	 *  Fetch every source's mirror — pinned ones included, that is the point —
	 *  then answer with the fresh standing. Fetch problems degrade to
	 *  warnings; a check for updates is never worth an error dialog.
	 */
	updatesRefresh: () => typedError<UpdatesReport_Serialize, string>(__TAURI_INVOKE("updates_refresh")),
	updateSetIgnored: (scope: Scope, kind: ItemKind, name: string, repo: string, ignored: boolean) => typedError<UpdatesReport_Serialize, string>(__TAURI_INVOKE("update_set_ignored", { scope, kind, name, repo, ignored })),
	/**
	 *  Hold a package at a version (or let it follow again) and apply the
	 *  change. The plan is whole-scope, like every apply: packages that follow
	 *  their source come current in the same pass, which is what following
	 *  means.
	 */
	packageSetRev: (scope: Scope, kind: ItemKind, name: string, rev: string | null) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("package_set_rev", { scope, kind, name, rev })),
	packageDiff: (scope: Scope, kind: ItemKind, name: string, from: VersionSel, to: VersionSel, harness: "claude" | "codex" | "opencode" | "cursor" | "pi" | "gemini" | "copilot" | null) => typedError<PackageDiff, string>(__TAURI_INVOKE("package_diff", { scope, kind, name, from, to, harness })),
	/**  Keep an edited install as a local fork, then render it in place. */
	packageFork: (scope: Scope, kind: ItemKind, name: string, harness: HarnessId) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("package_fork", { scope, kind, name, harness })),
	forkRename: (scope: Scope, kind: ItemKind, oldName: string, newName: string) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("fork_rename", { scope, kind, oldName, newName })),
	/**
	 *  Apply a scope with one package's edits discarded — the door back to
	 *  "the catalog's version wins", scoped to the package the user named so
	 *  a neighbour's edits are never taken along.
	 */
	applyDiscardEdits: (scope: Scope, kind: ItemKind, name: string, rev: string | null) => typedError<AuditView_Serialize, string>(__TAURI_INVOKE("apply_discard_edits", { scope, kind, name, rev })),
	packageFiles: (scope: Scope, kind: ItemKind, name: string) => typedError<PackageFile[], string>(__TAURI_INVOKE("package_files", { scope, kind, name })),
	packageFile: (scope: Scope, kind: ItemKind, name: string, path: string) => typedError<ItemSource, string>(__TAURI_INVOKE("package_file", { scope, kind, name, path })),
	packageReadme: (scope: Scope, kind: ItemKind, name: string) => typedError<{
	path: string,
	content: string,
	truncated: boolean,
} | null, string>(__TAURI_INVOKE("package_readme", { scope, kind, name })),
	packageMeta: (scope: Scope, kind: ItemKind, name: string) => typedError<PackageMeta_Serialize, string>(__TAURI_INVOKE("package_meta", { scope, kind, name })),
	/**
	 *  Zoom is set on the webview rather than by restyling the page: it holds
	 *  across reloads, and it scales the app's own titlebar along with
	 *  everything else, the way a browser scales a page. Holding across reloads
	 *  is also why the size is recorded here — the page forgets, the webview
	 *  does not.
	 */
	windowSetZoom: (percent: number) => typedError<null, string>(__TAURI_INVOKE("window_set_zoom", { percent })),
	/**  What the webview is showing, for a page with no memory of its own. */
	windowZoomState: () => __TAURI_INVOKE<ZoomState>("window_zoom_state"),
	windowMinimize: () => typedError<null, string>(__TAURI_INVOKE("window_minimize")),
	windowToggleMaximize: () => typedError<null, string>(__TAURI_INVOKE("window_toggle_maximize")),
	windowClose: () => typedError<null, string>(__TAURI_INVOKE("window_close")),
};

/* Constants */
export const ZOOM = {"min":50,"max":200,"step":10,"default":100} as const;

/* Types */
/**  One About row: what was found under one root. */
export type AboutFound = {
	root: string,
	kind: ItemKind,
	count: number,
};

/**
 *  The About tab's report: how the catalog's items were decided, what was
 *  found where, and everything wrong with it.
 */
export type AboutView = {
	mode: CatalogMode,
	found: AboutFound[],
	findings: CatalogFinding[],
};

export type AccountStatus = {
	signedIn: boolean,
	endpoint: string,
};

export type AntiPattern = {
	flag: string,
	detail: string,
	remediation: string,
};

/**  App preferences and the project registry — one settings file, nothing else. */
export type AppSettings = {
	schema: number,
	projects?: string[],
	/**  Per-harness override of the global root directory, keyed by harness id. */
	"harness-roots"?: { [key in string]: string },
	appearance?: Appearance,
	/**
	 *  Where the safety score starts warning and stops installing. These
	 *  live here rather than in a manifest on purpose: a manifest travels
	 *  with the repository it describes, and a catalog able to lower the bar
	 *  it is measured against is not being measured.
	 */
	safety?: Thresholds,
	/**
	 *  Packages whose update notifications are off. Here rather than in a
	 *  manifest for the same reason as `safety`: a notification preference
	 *  committed to a shared repository would silence a whole team.
	 */
	"ignored-updates"?: IgnoredUpdate[],
	/**
	 *  How large the interface draws, as a percent. Machine-local like
	 *  everything else in this file: how big text needs to be belongs to
	 *  the person and the display in front of them, not to a project.
	 */
	zoom?: number,
};

export type Appearance = "system" | "light" | "dark";

/**
 *  What the Audit page renders: drift rows plus the human-readable plan
 *  that would fix them.
 */
export type AuditView = AuditView_Serialize | AuditView_Deserialize;

/**
 *  What the Audit page renders: drift rows plus the human-readable plan
 *  that would fix them.
 */
export type AuditView_Deserialize = {
	scope: Scope,
	drift: DriftRow_Deserialize[],
	plan: string[],
	notes: string[],
	warnings: ItemWarning_Deserialize[],
	/**
	 *  What the safety rules found in the content installed here. Each row
	 *  carries two scores that are never combined: safety, which can hold an
	 *  install back, and quality, which only ever informs.
	 */
	safety: ItemSafety_Deserialize[],
	/**
	 *  Installations the plan would write but the safety gate holds back.
	 *  Kept apart from `safety` (which scores what is on disk) because the
	 *  two describe different bytes: an accept has to name the hash of what
	 *  apply would write, and only these rows carry it.
	 */
	heldBack: ItemSafety_Deserialize[],
	/**
	 *  Installations the plan would write that install with findings. The
	 *  same bytes as `safety` where an item is already installed unchanged;
	 *  for content that is new or changing, the findings that will need a
	 *  decision after apply — said before the write, since a dismissal is
	 *  about installed bytes and cannot be made on a plan.
	 */
	queued: ItemSafety_Deserialize[],
	/**
	 *  Set when this one scope couldn't be read at all — a corrupt or
	 *  future-version lock or manifest. Carried as data so one scope's
	 *  failure never blanks every other scope's audit (drift/plan/notes/
	 *  warnings/safety are empty alongside it).
	 */
	error: ScopeError | null,
};

/**
 *  What the Audit page renders: drift rows plus the human-readable plan
 *  that would fix them.
 */
export type AuditView_Serialize = {
	scope: Scope,
	drift: DriftRow_Serialize[],
	plan: string[],
	notes: string[],
	warnings: ItemWarning_Serialize[],
	/**
	 *  What the safety rules found in the content installed here. Each row
	 *  carries two scores that are never combined: safety, which can hold an
	 *  install back, and quality, which only ever informs.
	 */
	safety: ItemSafety_Serialize[],
	/**
	 *  Installations the plan would write but the safety gate holds back.
	 *  Kept apart from `safety` (which scores what is on disk) because the
	 *  two describe different bytes: an accept has to name the hash of what
	 *  apply would write, and only these rows carry it.
	 */
	heldBack: ItemSafety_Serialize[],
	/**
	 *  Installations the plan would write that install with findings. The
	 *  same bytes as `safety` where an item is already installed unchanged;
	 *  for content that is new or changing, the findings that will need a
	 *  decision after apply — said before the write, since a dismissal is
	 *  about installed bytes and cannot be made on a plan.
	 */
	queued: ItemSafety_Serialize[],
	/**
	 *  Set when this one scope couldn't be read at all — a corrupt or
	 *  future-version lock or manifest. Carried as data so one scope's
	 *  failure never blanks every other scope's audit (drift/plan/notes/
	 *  warnings/safety are empty alongside it).
	 */
	error?: ScopeError | null,
};

/**  One finding the publisher settled. */
export type AuthorDismissal = {
	reason: DismissReason,
	dismissedAt: string,
};

/**  One package a subscription offers, as the Packages table lists it. */
export type AvailablePackage = {
	kind: ItemKind,
	name: string,
	description: string | null,
	tags: Tag[],
	/**  The curated sets of this catalog that carry it. */
	bundles: string[],
	state: InstallState,
	/**
	 *  The source this name is already taken by, when that is a different
	 *  one. Invariant 4's refusal stays in the engine — this only shows the
	 *  collision before the click.
	 */
	collision: string | null,
};

/**
 *  A curated set with per-member state. Partly-installed is the derived
 *  pair below, computed from the members on every call and stored nowhere.
 */
export type BundleDetail = {
	name: string,
	description: string | null,
	version: string | null,
	category: string | null,
	members: BundleMemberRow[],
	/**  Members with an installation recorded in the lock, via any edge. */
	installedMembers: number,
	totalMembers: number,
	collision: string | null,
};

/**  One member of a curated set, with where it stands here. */
export type BundleMemberRow = {
	kind: ItemKind,
	name: string,
	state: InstallState,
};

/**  One curated set a catalog offers, as the Catalogs page lists it. */
export type BundleRow = {
	scope: Scope,
	source: string,
	name: string,
	description: string | null,
	version: string | null,
	category: string | null,
	/**  What it carries, each as the kind and name it installs under. */
	members: string[],
	installed: boolean,
};

export type CandidateGroup = 
/**  The person's own content in a local source. */
{ group: "own" } | 
/**
 *  Copied from a subscribed marketplace; its licence is shown and
 *  gates the copy.
 */
{ group: "marketplace"; source: string; repo: string; license: string | null; 
/**
 *  Whether kendex recognizes the licence as redistributable — a
 *  recognized one is confirmable, anything else needs a basis.
 */
licenseRecognized: boolean } | 
/**
 *  The installed copy of a marketplace package that no longer matches
 *  the marketplace's bytes — "your edited copy", shown beside the
 *  original and gated by the same licence.
 */
{ group: "edited"; source: string; repo: string; license: string | null; licenseRecognized: boolean } | 
/**  On disk, managed by nothing — captured the way adopt captures. */
{ group: "unmanaged" };

export type CandidateOrigin = {
	group: CandidateGroup,
	/**  Every place these exact bytes were seen. */
	locations: string[],
	/**  Content identity — what apply revalidates before copying. */
	hash: string,
};

export type CapabilityRow = {
	harness: HarnessId,
	kind: ItemKind,
	caps: KindCaps,
};

/**
 *  What a browse read addresses: a subscription, or a GitHub repository
 *  browsed before anyone subscribes to it. The second fetches into the same
 *  store a later subscription reads from, so subscribing never downloads
 *  twice and the pages keep working across the switch.
 */
export type Catalog = { by: "subscription"; scope: Scope; source: string } | 
/**
 *  A GitHub repository, in any spelling `repo_move::owner_repo` folds
 *  to the canonical `owner/repo` everything is keyed by.
 */
{ by: "repo"; repo: string };

/**  Something wrong with a catalog, said in the catalog author's terms. */
export type CatalogFinding = {
	location: string,
	problem: string,
	fix: string,
};

/**
 *  The catalog's own claims about the plugin an item ships in — read-side
 *  display only, never intent.
 */
export type CatalogGroupMeta = {
	version: string | null,
	description: string | null,
	author: string | null,
	license: string | null,
	homepage: string | null,
	category: string | null,
};

/**
 *  How a source's items were decided — the fixed precedence: a plugin
 *  registry wins outright, else a parsed control file's declared layout
 *  (`[catalog]` overriding which dirs), else the search table; a broken
 *  control file makes the source unusable, never a different mode.
 */
export type CatalogMode = "plugin-registry" | "explicit" | "discovered" | "unusable";

export type CatalogSummary = {
	/**  `owner/repo`, a path, or `local` — what the catalog is. */
	provenance: string,
	/**
	 *  The canonical `owner/repo` the provenance folds to on GitHub — what
	 *  a subscription's `repo_key` and a directory row are matched by,
	 *  however the declaration spells it.
	 */
	repoKey: string | null,
	/**  The commit being read, for a remote. */
	commit: string | null,
	/**  `[marketplace]` from the catalog's own kendex.toml. */
	meta: MarketplaceMeta | null,
	mode: CatalogMode,
	/**  Packages offered, by kind name. */
	counts: { [key in string]: number },
	/**  Set when the catalog is read from the store because a refresh failed. */
	warning: string | null,
	/**
	 *  For a repository: the subscription this machine already holds for
	 *  it, if any. A subscription answers with itself.
	 */
	subscription: SubscriptionRef | null,
};

export type CreateRequest = {
	/**  Folder and repository name; must be a plain installable spelling. */
	name: string,
	description: string,
	author: string,
	license: License,
	/**  The folder to create — its parent must exist, itself must not. */
	dir: string,
};

export type CustomHook = CustomHook_Serialize | CustomHook_Deserialize;

export type CustomHook_Deserialize = {
	/**
	 *  Stable identity: the registry key, the lock key, the UI row. Absent
	 *  in a hand-written entry until the editor's first save writes the
	 *  derived slug back (`hook::name_custom_hooks`); derivation is
	 *  deterministic, so an unnamed entry still plans consistently.
	 */
	name?: string | null,
	event: string,
	matcher: string | null,
	command: string,
	description: string | null,
	/**  Seconds; harnesses that count milliseconds convert on render. */
	timeout?: number | null,
	/**  Harness allowlist; `None` = every declared harness. */
	harnesses?: string[] | null,
	enabled?: boolean,
	agents?: HookAgents,
};

export type CustomHook_Serialize = {
	/**
	 *  Stable identity: the registry key, the lock key, the UI row. Absent
	 *  in a hand-written entry until the editor's first save writes the
	 *  derived slug back (`hook::name_custom_hooks`); derivation is
	 *  deterministic, so an unnamed entry still plans consistently.
	 */
	name?: string | null,
	event: string,
	matcher?: string | null,
	command: string,
	description?: string | null,
	/**  Seconds; harnesses that count milliseconds convert on render. */
	timeout?: number | null,
	/**  Harness allowlist; `None` = every declared harness. */
	harnesses?: string[] | null,
	enabled?: boolean,
	agents: HookAgents,
};

/**  What one record decided. */
export type DecisionRecord = DecisionRecord_Serialize | DecisionRecord_Deserialize;

/**  What one record decided. */
export type DecisionRecord_Deserialize = 
/**  A whole item's findings, read and accepted. */
({ kind: "accepted"; findings: number; grantedAt: string }) & { dismissedAt?: never; finding?: never; fingerprint?: never; reason?: never } | 
/**
 *  One finding, judged not to be a problem. `finding` is the current
 *  text of what it dismissed, present while that finding is still there.
 */
({ kind: "dismissed"; fingerprint: string; reason: DismissReason; dismissedAt: string; finding: Finding | null }) & { findings?: never; grantedAt?: never };

/**  What one record decided. */
export type DecisionRecord_Serialize = 
/**  A whole item's findings, read and accepted. */
({ kind: "accepted"; findings: number; grantedAt: string }) & { dismissedAt?: never; finding?: never; fingerprint?: never; reason?: never } | 
/**
 *  One finding, judged not to be a problem. `finding` is the current
 *  text of what it dismissed, present while that finding is still there.
 */
({ kind: "dismissed"; fingerprint: string; reason: DismissReason; dismissedAt: string; finding?: Finding | null }) & { findings?: never; grantedAt?: never };

/**
 *  What is recorded about one finding, read against the content in front
 *  of us now.
 */
export type DecisionState = DecisionState_Serialize | DecisionState_Deserialize;

/**
 *  What is recorded about one finding, read against the content in front
 *  of us now.
 */
export type DecisionState_Deserialize = 
/**
 *  Nobody has ruled on this finding for this content. `earlier` says why
 *  a previous ruling no longer applies, when there was one.
 */
({ state: "open"; earlier: string | null }) & { dismissedAt?: never; grantedAt?: never; publisher?: never; reason?: never } | 
/**  Judged not to be a problem, for exactly this content. */
({ state: "dismissed"; reason: DismissReason; dismissedAt: string }) & { earlier?: never; grantedAt?: never; publisher?: never } | 
/**
 *  The catalog that publishes this content committed a review saying
 *  this finding is not a problem, and that review still describes the
 *  exact bytes we fetched. It is reported, not hidden: `publisher` is
 *  the source the record was read from, recorded when it was read, so a
 *  person can weigh whose judgement this is.
 */
({ state: "author-dismissed"; reason: DismissReason; dismissedAt: string; publisher: string }) & { earlier?: never; grantedAt?: never } | 
/**
 *  Covered by an acceptance of the whole item: every finding on it was
 *  read and the item installed anyway.
 */
({ state: "accepted"; grantedAt: string }) & { dismissedAt?: never; earlier?: never; publisher?: never; reason?: never };

/**
 *  What is recorded about one finding, read against the content in front
 *  of us now.
 */
export type DecisionState_Serialize = 
/**
 *  Nobody has ruled on this finding for this content. `earlier` says why
 *  a previous ruling no longer applies, when there was one.
 */
({ state: "open"; earlier?: string | null }) & { dismissedAt?: never; grantedAt?: never; publisher?: never; reason?: never } | 
/**  Judged not to be a problem, for exactly this content. */
({ state: "dismissed"; reason: DismissReason; dismissedAt: string }) & { earlier?: never; grantedAt?: never; publisher?: never } | 
/**
 *  The catalog that publishes this content committed a review saying
 *  this finding is not a problem, and that review still describes the
 *  exact bytes we fetched. It is reported, not hidden: `publisher` is
 *  the source the record was read from, recorded when it was read, so a
 *  person can weigh whose judgement this is.
 */
({ state: "author-dismissed"; reason: DismissReason; dismissedAt: string; publisher: string }) & { earlier?: never; grantedAt?: never } | 
/**
 *  Covered by an acceptance of the whole item: every finding on it was
 *  read and the item installed anyway.
 */
({ state: "accepted"; grantedAt: string }) & { dismissedAt?: never; earlier?: never; publisher?: never; reason?: never };

/**
 *  A scope whose decisions could not be read, carried as data beside the
 *  ones that could. A view promising every decision must say which
 *  scopes it is not speaking for, never silently skip them.
 */
export type DecisionsScopeError = {
	scope: Scope,
	error: ScopeError,
};

export type DecisionsView = DecisionsView_Serialize | DecisionsView_Deserialize;

export type DecisionsView_Deserialize = {
	decisions: RecordedDecision_Deserialize[],
	errors: DecisionsScopeError[],
};

export type DecisionsView_Serialize = {
	decisions: RecordedDecision_Serialize[],
	errors: DecisionsScopeError[],
};

/**  One rule firing once, and what it cost. */
export type Deduction = {
	rule: string,
	location: string,
	severity: Severity,
	points: number,
	/**  A later hit from a rule that has already been counted in full. */
	repeat: boolean,
};

/**  A harness found on this machine. */
export type DetectedHarness = {
	harness: HarnessId,
	/**  The directory whose existence marks the harness as installed. */
	root: string,
	version: string | null,
};

export type DimensionScore = {
	dimension: string,
	weightPercent: number,
	scorePercent: number,
};

export type DirectoryBundle = {
	name: string,
	description: string | null,
	memberCount: number,
};

export type DirectoryPackage = {
	kind: string,
	name: string,
	description: string | null,
	safetyScore: number | null,
};

export type DirectoryRow = {
	repo: string,
	/**
	 *  The canonical key a subscription's `repo_key` is compared with, so
	 *  the row can flip to Subscribed from the live subscription list.
	 */
	repoKey: string | null,
	name: string,
	description: string | null,
	tags: string[],
	featured: boolean,
	packageCount: number,
	bundleCount: number,
	subscribed: boolean,
	packages: DirectoryPackage[],
	bundles: DirectoryBundle[],
};

export type DirectoryView = {
	rows: DirectoryRow[],
	/**
	 *  When the served list was actually fetched (ISO-8601) — the "as of"
	 *  line when `stale` is true, the "updated" line otherwise.
	 */
	fetchedAt: string,
	stale: boolean,
};

/**
 *  Why a finding was dismissed. Every reason is a claim about the content
 *  — a project's dismissals travel with the repository, so a reason must
 *  mean the same thing to whoever reads it next, and none of them may be
 *  one person's tolerance for risk.
 */
export type DismissReason = 
/**  The rule misread this: nothing here does what the finding says. */
"wrong-call" | 
/**  The flagged behaviour is what this item is for. */
"intended" | 
/**
 *  The content is from a source the reviewer trusts. Bound to that
 *  source's identity: the same bytes from somewhere else are a
 *  different question.
 */
"trusted-source";

/**
 *  One dismissed finding, keyed in its snapshot by the finding's
 *  fingerprint.
 */
export type Dismissal = Dismissal_Serialize | Dismissal_Deserialize;

/**
 *  One dismissed finding, keyed in its snapshot by the finding's
 *  fingerprint.
 */
export type Dismissal_Deserialize = {
	reason: DismissReason,
	"dismissed-at": string,
	/**
	 *  The source identity a `TrustedSource` dismissal trusted — the
	 *  resolved provenance the lock records, or the git origin of an
	 *  unmanaged item's files. Absent for the other reasons.
	 */
	source?: string | null,
};

/**
 *  One dismissed finding, keyed in its snapshot by the finding's
 *  fingerprint.
 */
export type Dismissal_Serialize = {
	reason: DismissReason,
	"dismissed-at": string,
	/**
	 *  The source identity a `TrustedSource` dismissal trusted — the
	 *  resolved provenance the lock records, or the git origin of an
	 *  unmanaged item's files. Absent for the other reasons.
	 */
	source?: string | null,
};

/**
 *  What a dismissal came back with: the scope's fresh view, and exactly
 *  what was written.
 */
export type Dismissed = Dismissed_Serialize | Dismissed_Deserialize;

/**
 *  One record a dismissal wrote, as an undo names it: the same key and
 *  fingerprint the registry uses, and the timestamp that pins this exact
 *  record so an old undo cannot delete a newer decision at the same key.
 */
export type DismissedRecord = {
	key: string,
	fingerprint: string,
	dismissedAt: string,
};

/**
 *  What a dismissal came back with: the scope's fresh view, and exactly
 *  what was written.
 */
export type Dismissed_Deserialize = {
	view: AuditView_Deserialize,
	records: DismissedRecord[],
};

/**
 *  What a dismissal came back with: the scope's fresh view, and exactly
 *  what was written.
 */
export type Dismissed_Serialize = {
	view: AuditView_Serialize,
	records: DismissedRecord[],
};

/**
 *  Why an installation diverged, when the plan can tell. `LocalEdit`,
 *  `Both` and `UnmanagedContent` are the causes that block writes: bytes
 *  kendex did not write are on disk and only an explicit choice may take
 *  them.
 */
export type DriftCause = "upstream-changed" | "local-edit" | "both" | 
/**
 *  Files are already where a declaration installs, and no lock entry
 *  says kendex put them there. The two ways out are opposite
 *  directions: adopt keeps the files, `replace_unmanaged` keeps the
 *  declaration.
 */
"unmanaged-content";

export type DriftRow = DriftRow_Serialize | DriftRow_Deserialize;

export type DriftRow_Deserialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	state: DriftState,
	detail: string,
	cause?: DriftCause | null,
};

export type DriftRow_Serialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	state: DriftState,
	detail: string,
	cause?: DriftCause | null,
};

export type DriftState = 
/**  Declared but not on disk (or never recorded). */
"missing" | 
/**  On disk but no longer matching declaration + source. */
"stale" | 
/**  Recorded in the lock but no longer declared. */
"orphaned" | 
/**  On disk in a managed surface, but not ours. */
"unmanaged" | 
/**  Needs a human: foreign symlink, occupied target, or provenance clash. */
"conflict";

/**
 *  What the Customize page needs to offer real choices: the names already
 *  declared here plus the skills any ready source can supply.
 */
export type EditorInventory = {
	declaredAgents: string[],
	declaredSkills: string[],
	availableSkills: string[],
	harnesses: HarnessId[],
	/**
	 *  The events a hook can be written against, and when each fires. Sent
	 *  rather than spelled out in the UI so the picker cannot offer an
	 *  event the validator would then reject.
	 */
	hookEvents: HookEvent[],
};

/**
 *  Whether the harness runs what kendex writes, or only reads it as prose.
 *  `managed` says kendex can write and track an artifact; it never said the
 *  tool would act on it, and a safety hook must not read as protection on a
 *  tool that can merely suggest it.
 */
export type Enforcement = 
/**  The harness executes the command and honors its result. */
"enforced" | 
/**  Rendered as instructions the model is free to ignore. */
"advisory" | 
/**
 *  Nothing here executes: every kind but Hook, and the harnesses kendex
 *  declares no hook surface for.
 */
"not-applicable";

export type FileDiff = {
	/**  Forward-slash relative path, whatever the platform. */
	path: string,
	status: FileStatus,
	additions: number,
	deletions: number,
	/**  One side was not valid UTF-8 and is shown lossily. */
	lossy: boolean,
	hunks: Hunk[],
};

/**
 *  How an observed item exists on disk. Kinds that live as entries inside a
 *  shared config file (MCP servers, some hooks) are `ConfigEntry`.
 */
export type FileState = { state: "file" } | { state: "dir" } | { state: "symlink"; target: string; broken: boolean } | { state: "config-entry" };

export type FileStatus = "added" | "removed" | "modified" | 
/**  Holds a NUL byte on either side — compared, never rendered as text. */
"binary" | 
/**  Past the size or line budget — reported, not diffed. */
"too-large";

/**
 *  One safety problem, where it is, and what to do about it. The message
 *  never holds a matched secret — only its fingerprint (invariant of
 *  `secret::fingerprint_secret`).
 */
export type Finding = {
	rule: string,
	severity: Severity,
	/**  The file and line, or the config key that holds the entry. */
	location: string,
	message: string,
	remediation: string,
};

/**
 *  One finding as a thing a person can rule on. Sits beside the finding it
 *  is about — `ItemSafety.decisions[i]` speaks for `ItemSafety.findings[i]`.
 */
export type FindingDecision = FindingDecision_Serialize | FindingDecision_Deserialize;

/**
 *  One finding as a thing a person can rule on. Sits beside the finding it
 *  is about — `ItemSafety.decisions[i]` speaks for `ItemSafety.findings[i]`.
 */
export type FindingDecision_Deserialize = {
	/**
	 *  This finding's identity within its item — what a recorded decision
	 *  is keyed by, and what tells one occurrence of a finding from another
	 *  when the same bytes are read through several tools.
	 */
	fingerprint: string,
	/**
	 *  Names exactly this finding on exactly this content. Opaque to the
	 *  UI; the only thing a dismiss command accepts. Absent where the
	 *  content cannot be read here — there is nothing exact to bind a
	 *  decision to, so none can be made.
	 */
	token: string | null,
	state: DecisionState_Deserialize,
};

/**
 *  One finding as a thing a person can rule on. Sits beside the finding it
 *  is about — `ItemSafety.decisions[i]` speaks for `ItemSafety.findings[i]`.
 */
export type FindingDecision_Serialize = {
	/**
	 *  This finding's identity within its item — what a recorded decision
	 *  is keyed by, and what tells one occurrence of a finding from another
	 *  when the same bytes are read through several tools.
	 */
	fingerprint: string,
	/**
	 *  Names exactly this finding on exactly this content. Opaque to the
	 *  UI; the only thing a dismiss command accepts. Absent where the
	 *  content cannot be read here — there is nothing exact to bind a
	 *  decision to, so none can be made.
	 */
	token: string | null,
	state: DecisionState_Serialize,
};

/**
 *  Where a fork came from. A fork keeps the item's installed name — the
 *  declaration just switches to the local source, so nothing that depends
 *  on the name breaks — and this records what it replaced. Manifest, not
 *  lock, because the package page keeps reading it after any cache loss.
 */
export type ForkProvenance = ForkProvenance_Serialize | ForkProvenance_Deserialize;

/**
 *  Where a fork came from. A fork keeps the item's installed name — the
 *  declaration just switches to the local source, so nothing that depends
 *  on the name breaks — and this records what it replaced. Manifest, not
 *  lock, because the package page keeps reading it after any cache loss.
 */
export type ForkProvenance_Deserialize = {
	/**  Declared source name the original installed from. */
	source: string,
	repo?: string | null,
	/**  The source commit the edited install was based on, when known. */
	commit?: string | null,
	"forked-at": string,
};

/**
 *  Where a fork came from. A fork keeps the item's installed name — the
 *  declaration just switches to the local source, so nothing that depends
 *  on the name breaks — and this records what it replaced. Manifest, not
 *  lock, because the package page keeps reading it after any cache loss.
 */
export type ForkProvenance_Serialize = {
	/**  Declared source name the original installed from. */
	source: string,
	repo?: string | null,
	/**  The source commit the edited install was based on, when known. */
	commit?: string | null,
	"forked-at": string,
};

/**  Typed `[agent-frontmatter.<harness>.<agent>]` overrides — v1's field set. */
export type FrontmatterOverrides = FrontmatterOverrides_Serialize | FrontmatterOverrides_Deserialize;

/**  Typed `[agent-frontmatter.<harness>.<agent>]` overrides — v1's field set. */
export type FrontmatterOverrides_Deserialize = {
	color: string | null,
	model: string | null,
	"deny-tools": string[] | null,
	/**
	 *  Allow-only tool intent: replaces a source-side `tools:` allowlist for
	 *  this harness. Distinct from `deny_tools`, which only narrows.
	 */
	"allow-tools": string[] | null,
	"allowed-subagents": string[] | null,
	pane: boolean | null,
	background: boolean | null,
	effort: string | null,
	isolation: string | null,
	memory: string | null,
	mode: string | null,
	"sandbox-mode": string | null,
	"model-reasoning-effort": string | null,
	"nickname-candidates": string[] | null,
};

/**  Typed `[agent-frontmatter.<harness>.<agent>]` overrides — v1's field set. */
export type FrontmatterOverrides_Serialize = {
	color?: string | null,
	model?: string | null,
	"deny-tools"?: string[] | null,
	/**
	 *  Allow-only tool intent: replaces a source-side `tools:` allowlist for
	 *  this harness. Distinct from `deny_tools`, which only narrows.
	 */
	"allow-tools"?: string[] | null,
	"allowed-subagents"?: string[] | null,
	pane?: boolean | null,
	background?: boolean | null,
	effort?: string | null,
	isolation?: string | null,
	memory?: string | null,
	mode?: string | null,
	"sandbox-mode"?: string | null,
	"model-reasoning-effort"?: string | null,
	"nickname-candidates"?: string[] | null,
};

/**  What git says about the folder, locally. Nothing here asks the network. */
export type GitReadiness = {
	repository: boolean,
	/**  `Some(false)` when uncommitted changes exist; `None` outside a repo. */
	clean: boolean | null,
	/**  The `origin` remote URL, verbatim. */
	remote: string | null,
	/**
	 *  `owner/repo` parsed out of a GitHub remote — the candidate the
	 *  submit preflight will verify, never a verdict by itself.
	 */
	candidate: string | null,
	/**
	 *  Commits ahead of the tracked upstream, when one is configured. What
	 *  this machine knows — the remote may have moved since the last fetch.
	 */
	ahead: number | null,
};

export type HarnessId = "claude" | "codex" | "opencode" | "cursor" | "pi" | "gemini" | "copilot";

/**
 *  Whose hold keeps a place at its revision — what the Follow source
 *  switch may release, and what it may not.
 */
export type HoldOwner = 
/**  This declaration's own `rev`: the switch releases it. */
{ kind: "package" } | 
/**  The source is pinned as a whole; released where the source is declared. */
{ kind: "source"; name: string } | 
/**  Propagated from the bundle or package that pulled this one in. */
{ kind: "parent" };

export type HookAgents = 
/**  `"all"`, a role name, or a single agent name. */
string | string[];

/**
 *  How one custom hook reaches one harness, for the editor's per-hook line.
 *  Computed by `kendex_core::hook::delivery` — the same decision the engine
 *  installs by — so the words on screen cannot drift from what applies.
 */
export type HookDelivery = {
	harness: HarnessId,
	mode: HookDeliveryMode,
	/**  Why nothing installs, for `unavailable` rows. */
	note: string | null,
};

export type HookDeliveryMode = 
/**  Registered in the harness's own hook configuration — it runs. */
"runs" | 
/**  Claude's per-agent hooks block — it runs, for the chosen agents. */
"runs-in-agent-file" | 
/**  Written into the agents as instructions — nothing enforces it. */
"instructions" | 
/**  No surface for it here at all. */
"unavailable";

export type HookEvent = {
	name: string,
	fires: string,
};

export type Hunk = {
	header: string,
	lines: Line[],
};

/**
 *  A package whose update notifications are switched off, by everything
 *  that identifies it: an ignore for one project's `gh` skill from one
 *  repository must not silence another project's unrelated `gh`.
 */
export type IgnoredUpdate = {
	/**  `"global"` or the project root path. */
	scope: string,
	kind: ItemKind,
	name: string,
	repo: string,
};

/**  One importable package, with every byte origin that offers it. */
export type ImportCandidate = {
	kind: ItemKind,
	name: string,
	/**
	 *  Why a harness would refuse this name, when one would — the wizard
	 *  requires a different destination name then.
	 */
	nameProblem: string | null,
	/**
	 *  Distinct byte variants, presentation-ordered own → marketplace →
	 *  edited → unmanaged. Identical bytes collapse to one entry listing
	 *  every location, under the strictest provenance among them; differing
	 *  bytes stay separate for the person to choose.
	 */
	origins: CandidateOrigin[],
};

/**  What one apply wrote, for the wizard's summary line. */
export type ImportOutcome = {
	written: string[],
	/**  Selections whose exact bytes were already at the destination. */
	alreadyPresent: string[],
};

/**  What the wizard chose for one candidate. */
export type ImportSelection = {
	kind: ItemKind,
	/**  The inventory name the bytes are found under. */
	name: string,
	/**
	 *  The name to write into the catalog — the inventory name unless a
	 *  harness would refuse it.
	 */
	destination: string,
	/**  Which bytes: the chosen origin's hash. */
	hash: string,
	/**
	 *  Licensed-origin only: the person confirms the shown, recognized
	 *  licence permits republishing. An unrecognized licence cannot be
	 *  confirmed — it needs a basis.
	 */
	licenseConfirmed?: boolean,
	/**
	 *  Licensed-origin with no recognized licence: the person's stated
	 *  basis for copying ("author granted permission", say). Never
	 *  synthesized.
	 */
	licenseBasis?: string | null,
};

export type InstallDefaults = {
	harnesses?: HarnessId[],
	method?: Method,
};

/**  One selected package, by the kind and name the catalog offers it under. */
export type InstallItem = {
	kind: ItemKind,
	name: string,
};

/**  Whether one offered package exists in this scope. */
export type InstallState = 
/**  An installation from this subscription is recorded in the lock. */
"installed" | 
/**  Offered, nothing installed. */
"available" | 
/**
 *  Asked for — declared, or carried by a declared bundle — but the
 *  safety gate refuses to install it.
 */
"held-back-by-safety" | 
/**
 *  The bundle names a member the catalog no longer offers — renamed or
 *  removed upstream. A row saying so, never a dead page: the member list
 *  is catalog-authored text and one bad entry cannot break the read.
 */
"not-offered" | 
/**
 *  The user removed this member and the removal is recorded, so nothing
 *  derives it back. The row says it was their choice and offers Restore —
 *  installing it again clears the record (invariant 2 stays intact).
 */
"removed-by-you";

/**  One declared item: `[agents.<name>]` / `[skills.<name>]`. */
export type ItemDecl = ItemDecl_Serialize | ItemDecl_Deserialize;

/**  One declared item: `[agents.<name>]` / `[skills.<name>]`. */
export type ItemDecl_Deserialize = {
	source: string,
	harnesses: HarnessId[] | null,
	method: Method | null,
	/**
	 *  Which revision of the source this item reads, outranking the
	 *  source-level `rev`. Same semantics: a full commit id pins, a tag or
	 *  branch tracks. Present means the item holds here while the source
	 *  moves — this is what "manual updates" is; absent means the item
	 *  follows the source.
	 */
	rev?: string | null,
	enabled?: boolean,
};

/**  One declared item: `[agents.<name>]` / `[skills.<name>]`. */
export type ItemDecl_Serialize = {
	source: string,
	harnesses?: HarnessId[] | null,
	method?: Method | null,
	/**
	 *  Which revision of the source this item reads, outranking the
	 *  source-level `rev`. Same semantics: a full commit id pins, a tag or
	 *  branch tracks. Present means the item holds here while the source
	 *  moves — this is what "manual updates" is; absent means the item
	 *  follows the source.
	 */
	rev?: string | null,
	enabled: boolean,
};

export type ItemKind = "agent" | "skill" | "hook" | "command" | "mcp-server" | "plugin" | "pi-extension";

/**
 *  One installation's two scores and everything behind them. Safety and
 *  quality sit side by side and are never combined: one answers whether the
 *  content is dangerous, the other whether it is any good, and averaging
 *  them would let a well-written attack outscore a clumsy honest skill.
 */
export type ItemSafety = ItemSafety_Serialize | ItemSafety_Deserialize;

/**
 *  One installation's two scores and everything behind them. Safety and
 *  quality sit side by side and are never combined: one answers whether the
 *  content is dangerous, the other whether it is any good, and averaging
 *  them would let a well-written attack outscore a clumsy honest skill.
 */
export type ItemSafety_Deserialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	/**
	 *  The artifact's path, or the config file holding the entry — what
	 *  every finding's location is relative to.
	 */
	location: string,
	safety: SafetyScore,
	/**  Advisory only, and absent for kinds with no authored prose. */
	quality: QualityScore | null,
	findings: Finding[],
	/**  Rules that apply to this kind but had no bytes to read here. */
	skipped: SkippedRule[],
	verdict: Verdict,
	/**  Why the verdict is what it is, in sentences. */
	reasons: string[],
	/**
	 *  The identity of the bytes the rules read — the reduced input the
	 *  findings came out of, budgets and lossy decoding included.
	 */
	contentHash: string,
	/**
	 *  The identity of the complete bytes, or of the exact config entry. A
	 *  decision binds to this and the flag that grants one carries it, so it
	 *  is what a reviewer is accepting. `None` where the bytes cannot be
	 *  reached from here at all.
	 */
	reviewHash: string | null,
	/**
	 *  Where the bytes came from, as kendex itself resolved and recorded it.
	 *  What a trusted-source dismissal binds to. `None` for anything kendex
	 *  did not install — a remote url found near the files is not a source
	 *  to trust by, since the files could have written it.
	 */
	provenance: string | null,
	override: OverrideState,
	/**  What has been decided about each finding, in the findings' order. */
	decisions: FindingDecision_Deserialize[],
};

/**
 *  One installation's two scores and everything behind them. Safety and
 *  quality sit side by side and are never combined: one answers whether the
 *  content is dangerous, the other whether it is any good, and averaging
 *  them would let a well-written attack outscore a clumsy honest skill.
 */
export type ItemSafety_Serialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	/**
	 *  The artifact's path, or the config file holding the entry — what
	 *  every finding's location is relative to.
	 */
	location: string,
	safety: SafetyScore,
	/**  Advisory only, and absent for kinds with no authored prose. */
	quality: QualityScore | null,
	findings: Finding[],
	/**  Rules that apply to this kind but had no bytes to read here. */
	skipped: SkippedRule[],
	verdict: Verdict,
	/**  Why the verdict is what it is, in sentences. */
	reasons: string[],
	/**
	 *  The identity of the bytes the rules read — the reduced input the
	 *  findings came out of, budgets and lossy decoding included.
	 */
	contentHash: string,
	/**
	 *  The identity of the complete bytes, or of the exact config entry. A
	 *  decision binds to this and the flag that grants one carries it, so it
	 *  is what a reviewer is accepting. `None` where the bytes cannot be
	 *  reached from here at all.
	 */
	reviewHash: string | null,
	/**
	 *  Where the bytes came from, as kendex itself resolved and recorded it.
	 *  What a trusted-source dismissal binds to. `None` for anything kendex
	 *  did not install — a remote url found near the files is not a source
	 *  to trust by, since the files could have written it.
	 */
	provenance: string | null,
	override: OverrideState,
	/**  What has been decided about each finding, in the findings' order. */
	decisions: FindingDecision_Serialize[],
};

export type ItemSource = {
	path: string,
	content: string,
	truncated: boolean,
};

/**
 *  A per-item render or parse warning, with the fix when there is one —
 *  shown in plan previews, the CLI, and the Audit page.
 */
export type ItemWarning = ItemWarning_Serialize | ItemWarning_Deserialize;

/**
 *  A per-item render or parse warning, with the fix when there is one —
 *  shown in plan previews, the CLI, and the Audit page.
 */
export type ItemWarning_Deserialize = {
	kind: ItemKind,
	name: string,
	harness: HarnessId | null,
	message: string,
	remediation: string | null,
};

/**
 *  A per-item render or parse warning, with the fix when there is one —
 *  shown in plan previews, the CLI, and the Audit page.
 */
export type ItemWarning_Serialize = {
	kind: ItemKind,
	name: string,
	harness?: HarnessId | null,
	message: string,
	remediation?: string | null,
};

/**
 *  What each operation supports for one harness × kind. `observe` is derived
 *  from adapter surface declarations (tested); mutation columns land with
 *  their phases and stay honest through those phases' tests.
 */
export type KindCaps = {
	observe: OpSupport,
	adopt: OpSupport,
	install: OpSupport,
	toggle: OpSupport,
	remove: OpSupport,
	refresh: OpSupport,
	/**
	 *  The kind the harness actually stores this one as, when it has no
	 *  surface of its own to write to. `observe` keeps describing the
	 *  item's own surfaces; what a mutation writes is observable at the
	 *  emitted kind's, which is where the honesty check looks.
	 */
	installsAs: ItemKind | null,
	/**
	 *  Only Hook rows carry anything but `NotApplicable` — the axis exists
	 *  to separate a hook the tool runs from one it merely reads.
	 */
	enforcement: Enforcement,
};

export type License = "mit" | "apache2" | 
/**  Valid locally forever; blocks submission until chosen. */
"none-yet";

export type Line = {
	kind: LineKind,
	text: string,
	oldNo: number | null,
	newNo: number | null,
};

export type LineKind = "context" | "add" | "remove";

export type LoginStart = {
	deviceCode: string,
	userCode: string,
	/**  The page to open, with the code already in it. */
	verificationUrl: string,
	intervalSeconds: number,
};

export type Manifest = Manifest_Serialize | Manifest_Deserialize;

export type Manifest_Deserialize = {
	schema: number,
	sources?: { [key in string]: SourceDecl_Deserialize },
	install?: InstallDefaults,
	agents?: { [key in string]: ItemDecl_Deserialize },
	skills?: { [key in string]: ItemDecl_Deserialize },
	hooks?: { [key in string]: ItemDecl_Deserialize },
	commands?: { [key in string]: ItemDecl_Deserialize },
	"mcp-servers"?: { [key in string]: ItemDecl_Deserialize },
	/**
	 *  Plugins are observe + enable/disable only; the key is
	 *  `name@marketplace`, provenance lives in the lock.
	 */
	plugins?: { [key in string]: PluginDecl },
	/**
	 *  Installed bundles: a curated set the catalog offers under one name.
	 *  What the set holds is the catalog's to say and derives on every plan;
	 *  this records only that the set is installed, and how its members
	 *  install — the same choices any declaration makes.
	 */
	bundles?: { [key in string]: ItemDecl_Deserialize },
	"pi-extensions"?: { [key in string]: ItemDecl_Deserialize },
	/**
	 *  Items the user removed and wants kept removed, by kind: a dependency
	 *  another item requires, or a member of an installed bundle. A refresh
	 *  honors these instead of re-deriving what was taken away, and the item
	 *  that wanted them says so in the audit.
	 */
	suppressed?: Partial<{ [key in ItemKind]: string[] }>,
	/**
	 *  Optional dependencies taken at install time, per item that offers
	 *  them. A choice, so it belongs here and survives refresh, cache loss,
	 *  and other machines; what those choices pull in does not.
	 */
	"optional-dependencies"?: { [key in string]: string[] },
	/**
	 *  Reviews of content the safety gate blocked, keyed by installation.
	 *  Each one binds to the content, the rule set and the findings it was
	 *  granted against, so it stops applying the moment any of them moves.
	 */
	"safety-overrides"?: { [key in string]: SafetyOverride_Deserialize },
	/**
	 *  Findings judged not to be problems, keyed by installation, one
	 *  snapshot of the reviewed content per installation with each
	 *  dismissal beneath it. A dismissal settles a question and never
	 *  unblocks anything.
	 */
	"safety-reviews"?: { [key in string]: SafetyReview_Deserialize },
	"agent-skills"?: { [key in string]: string[] },
	"agent-launch-instructions"?: { [key in string]: string },
	"agent-additional-instructions"?: { [key in string]: string },
	"skill-instructions"?: { [key in string]: string },
	/**  `[agent-frontmatter.<harness>.<agent>]`. */
	"agent-frontmatter"?: { [key in string]: { [key in string]: FrontmatterOverrides_Deserialize } },
	"custom-hooks"?: CustomHook_Deserialize[],
	/**
	 *  Forked items by kind and name — `[forks.skill.<name>]`. The name is
	 *  the item's installed name, unchanged by forking.
	 */
	forks?: Partial<{ [key in ItemKind]: { [key in string]: ForkProvenance_Deserialize } }>,
};

export type Manifest_Serialize = {
	schema: number,
	sources?: { [key in string]: SourceDecl_Serialize },
	install: InstallDefaults,
	agents?: { [key in string]: ItemDecl_Serialize },
	skills?: { [key in string]: ItemDecl_Serialize },
	hooks?: { [key in string]: ItemDecl_Serialize },
	commands?: { [key in string]: ItemDecl_Serialize },
	"mcp-servers"?: { [key in string]: ItemDecl_Serialize },
	/**
	 *  Plugins are observe + enable/disable only; the key is
	 *  `name@marketplace`, provenance lives in the lock.
	 */
	plugins?: { [key in string]: PluginDecl },
	/**
	 *  Installed bundles: a curated set the catalog offers under one name.
	 *  What the set holds is the catalog's to say and derives on every plan;
	 *  this records only that the set is installed, and how its members
	 *  install — the same choices any declaration makes.
	 */
	bundles?: { [key in string]: ItemDecl_Serialize },
	"pi-extensions"?: { [key in string]: ItemDecl_Serialize },
	/**
	 *  Items the user removed and wants kept removed, by kind: a dependency
	 *  another item requires, or a member of an installed bundle. A refresh
	 *  honors these instead of re-deriving what was taken away, and the item
	 *  that wanted them says so in the audit.
	 */
	suppressed?: Partial<{ [key in ItemKind]: string[] }>,
	/**
	 *  Optional dependencies taken at install time, per item that offers
	 *  them. A choice, so it belongs here and survives refresh, cache loss,
	 *  and other machines; what those choices pull in does not.
	 */
	"optional-dependencies"?: { [key in string]: string[] },
	/**
	 *  Reviews of content the safety gate blocked, keyed by installation.
	 *  Each one binds to the content, the rule set and the findings it was
	 *  granted against, so it stops applying the moment any of them moves.
	 */
	"safety-overrides"?: { [key in string]: SafetyOverride_Serialize },
	/**
	 *  Findings judged not to be problems, keyed by installation, one
	 *  snapshot of the reviewed content per installation with each
	 *  dismissal beneath it. A dismissal settles a question and never
	 *  unblocks anything.
	 */
	"safety-reviews"?: { [key in string]: SafetyReview_Serialize },
	"agent-skills"?: { [key in string]: string[] },
	"agent-launch-instructions"?: { [key in string]: string },
	"agent-additional-instructions"?: { [key in string]: string },
	"skill-instructions"?: { [key in string]: string },
	/**  `[agent-frontmatter.<harness>.<agent>]`. */
	"agent-frontmatter"?: { [key in string]: { [key in string]: FrontmatterOverrides_Serialize } },
	"custom-hooks"?: CustomHook_Serialize[],
	/**
	 *  Forked items by kind and name — `[forks.skill.<name>]`. The name is
	 *  the item's installed name, unchanged by forking.
	 */
	forks?: Partial<{ [key in ItemKind]: { [key in string]: ForkProvenance_Serialize } }>,
};

export type MarketplaceMeta = {
	name?: string | null,
	description?: string | null,
	author?: string | null,
	license?: string | null,
	homepage?: string | null,
	tags?: string[],
};

/**
 *  One subscription as the Marketplaces page lists it: what it points at,
 *  how many packages it offers per kind, and what the catalog states about
 *  itself where its bytes are readable.
 */
export type MarketplaceRow = {
	scope: Scope,
	name: string,
	repo: string | null,
	/**
	 *  The canonical `owner/repo` a GitHub declaration folds to — what a
	 *  directory row is matched against, however the subscription spells it.
	 */
	repoKey: string | null,
	path: string | null,
	rev: string | null,
	/**  The commit the subscription reads right now, when the cache holds one. */
	commit: string | null,
	enabled: boolean,
	/**
	 *  Packages offered, by kind name — absent until the catalog has been
	 *  fetched and can be read.
	 */
	counts: { [key in string]: number } | null,
	/**  `[marketplace]` from the catalog's kendex.toml, where readable. */
	meta: MarketplaceMeta | null,
	/**  How the catalog's items were decided, where readable. */
	mode: CatalogMode | null,
};

export type Method = "symlink" | "copy";

/**
 *  One row that could not be computed keeps its place in the list with the
 *  reason, so a broken folder never hides the healthy ones.
 */
export type MineListRow = { state: "ready"; row: MineRow } | { state: "unreadable"; path: string; why: string };

/**  One Mine row, computed fresh from the folder on every ask. */
export type MineRow = {
	path: string,
	/**  The catalog's own name, or the folder leaf where it says nothing. */
	name: string,
	description: string | null,
	license: string | null,
	/**  Discovered packages per kind name. */
	counts: { [key in string]: number },
	bundles: number,
	/**
	 *  Whether a control file (`kendex.toml`) declares the layout — the
	 *  offers surface reads this to know what to offer.
	 */
	declared: boolean,
	breakage: number,
	heldBack: number,
	warned: number,
	advisory: number,
	/**  Every check finding, file-first, so the app can open each one. */
	findings: StatusFinding[],
	git: GitReadiness,
};

/**
 *  One item as the scanner found it — read-only truth, no interpretation of
 *  whether it is declared or managed.
 */
export type ObservedItem = {
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	scope: Scope,
	/**  Path of the artifact, or of the config file that contains the entry. */
	path: string,
	fileState: FileState,
	/**
	 *  Observable enabled/disabled state; `None` when the harness has no
	 *  observable toggle for this kind.
	 */
	enabled: boolean | null,
	/**  Best-effort provenance: git origin URL of the content's real location. */
	origin: string | null,
	description: string | null,
	/**
	 *  What this item says it is for. Empty when it says nothing — a tag is
	 *  something an author writes down, never something inferred from a
	 *  name, because a wrong guess is worse than no answer.
	 */
	tags: Tag[],
	/**
	 *  Unix seconds the primary file last changed, as `u32` because specta
	 *  refuses to export a 64-bit int (precision loss crossing the IPC
	 *  boundary) — good until year 2106. `None` where the item has no
	 *  single file of its own to stat (a config-entry kind, or a stat that
	 *  failed) — a shared file's mtime does not describe any one entry
	 *  inside it.
	 */
	modifiedAt: number | null,
	/**
	 *  Who ships this content, when a tool ships it itself — see
	 *  [`crate::vendor`]. `None` is the common case: the user's own.
	 */
	vendor: string | null,
};

/**  One offered write, previewed: the exact relative path and bytes. */
export type OfferPreview = {
	rel: string,
	bytes: string,
};

export type OpSupport = {
	project: boolean,
	global: boolean,
};

/**  Where one installation came from. */
export type Origin = 
/**
 *  Installed from a subscription: its declared alias and its repository
 *  (or path) as the lock recorded them.
 */
{ origin: "marketplace"; source: string; repo: string } | 
/**
 *  The user's own content in the local source — adopted, or forked off
 *  a marketplace item, in which case this names what it replaced.
 */
{ origin: "own"; forkedFrom: string | null } | 
/**  On disk and observed, managed by nothing. */
{ origin: "unmanaged" };

/**  Whether a recorded override still speaks for what is in front of us. */
export type OverrideState = 
/**  Nothing recorded for this installation. */
{ state: "absent" } | 
/**  Recorded, and still describing exactly this. */
{ state: "active" } | 
/**  Recorded, but what it was granted against has changed since. */
{ state: "stale"; why: string };

export type PackageDiff = {
	files: FileDiff[],
	totalAdditions: number,
	totalDeletions: number,
	/**  The comparison hit a budget; what is shown is a prefix, not the whole. */
	truncated: boolean,
};

/**
 *  One file inside the package, path relative to the package root with
 *  forward slashes whatever the platform.
 */
export type PackageFile = {
	path: string,
	size: number,
	isReadme: boolean,
};

/**
 *  One finding on an offered package, with the publisher's record about it
 *  when they have one. A settled finding is reported here and does not
 *  count toward the score or the verdict — the same answer the install
 *  gate gives, which is the only reason this preview is worth showing.
 */
export type PackageFinding = {
	settled: AuthorDismissal | null,
} & Finding;

export type PackageMeta = PackageMeta_Serialize | PackageMeta_Deserialize;

export type PackageMeta_Deserialize = {
	source: string,
	/**  `owner/repo`, when the source is remote. */
	repo: string | null,
	/**  A safe https link to the repository, when one can be formed. */
	repoUrl: string | null,
	/**  The declaration's hold, when it has one. */
	rev: string | null,
	/**  The content revision installed now. */
	current: VersionRef | null,
	installedAt: string | null,
	harnesses: HarnessId[],
	enabled: boolean,
	fork: ForkProvenance_Deserialize | null,
	catalog: CatalogGroupMeta | null,
};

export type PackageMeta_Serialize = {
	source: string,
	/**  `owner/repo`, when the source is remote. */
	repo: string | null,
	/**  A safe https link to the repository, when one can be formed. */
	repoUrl: string | null,
	/**  The declaration's hold, when it has one. */
	rev: string | null,
	/**  The content revision installed now. */
	current: VersionRef | null,
	installedAt: string | null,
	harnesses: HarnessId[],
	enabled: boolean,
	fork: ForkProvenance_Serialize | null,
	catalog: CatalogGroupMeta | null,
};

/**  What the available-package page shows before anything installs. */
export type PackagePreview = {
	kind: ItemKind,
	name: string,
	description: string | null,
	tags: Tag[],
	/**
	 *  The file a harness would load, capped for preview: a skill's
	 *  SKILL.md body, a command's or agent's body, a hook's script, an MCP
	 *  server's config. Control characters are shown, never acted on.
	 */
	readme: string | null,
	files: PackageFile[],
	/**  The curated sets of this catalog that carry it. */
	bundles: string[],
	collision: string | null,
};

/**  One package named in an unsubscribe preview. */
export type PackageRef = {
	kind: ItemKind,
	name: string,
};

/**
 *  One offered package's scores and the verdict today's thresholds give
 *  them — the dot in the Packages table and the findings on the
 *  available-package page.
 */
export type PackageSafety = {
	kind: ItemKind,
	name: string,
	/**
	 *  Every finding, each carrying whatever has already been decided about
	 *  it. One row, not two arrays a reader has to keep in step by index.
	 */
	findings: PackageFinding[],
	safety: SafetyScore,
	/**  Advisory, never blocking. */
	quality: QualityScore | null,
	skipped: SkippedRule[],
	verdict: Verdict,
	reasons: string[],
	contentHash: string,
	ruleset: number,
	/**  Whether a verified cache entry answered instead of a fresh score. */
	fromCache: boolean,
	/**  Who recorded the settled findings, when this package carries any. */
	publisher: string | null,
};

/**
 *  The available-package page's one payload: the preview beside the safety
 *  verdict the same content would face at install.
 */
export type PackageView = {
	preview: PackagePreview,
	safety: PackageSafety,
};

/**
 *  One declared plugin. The harness is part of the declaration because more
 *  than one tool reads an `enabledPlugins` map of its own: without it, a
 *  plugin meant for one tool would be switched on in every tool's settings,
 *  which is a claim about software the user never installed there.
 * 
 *  A declaration written before the harness was part of it belongs to Claude
 *  Code — the only tool whose plugin switch kendex ever wrote — so that is
 *  what an older manifest reads back as, and the next write records it.
 */
export type PluginDecl = {
	enabled?: boolean,
	harness?: HarnessId,
};

/**
 *  One preflight row. `ok: None` is "cannot be known from this machine
 *  right now" — shown, never guessed.
 */
export type PreflightCheck = {
	ok: boolean | null,
	label: string,
	/**  What to do when the row fails. */
	fix: string | null,
};

/**  One installation's origin, keyed the way the Library table joins it. */
export type ProvenanceRow = {
	scope: Scope,
	kind: ItemKind,
	name: string,
	harness: HarnessId,
	origin: Origin,
};

export type QualityScore = {
	score: number,
	dimensions: DimensionScore[],
	antiPatterns: AntiPattern[],
	/**
	 *  What the anti-patterns multiplied the weighted total by, as a
	 *  percentage. Floors at 50 — the penalty shapes a score, it does not
	 *  replace it.
	 */
	penaltyPercent: number,
};

/**  Whether a recorded decision still speaks for anything. */
export type RecordState = 
/**  Describing exactly what is installed now. */
{ state: "active" } | 
/**  Recorded, but what it was made against has changed since. */
{ state: "stale"; why: string } | 
/**  The item it was about is no longer installed here. */
{ state: "obsolete" };

/**
 *  One recorded decision, as the registry lists it. `key` is the manifest's
 *  own spelling and is what revoke takes back, so even an entry a hand edit
 *  mangled can still be withdrawn; the typed fields are parsed from it for
 *  display and absent where it does not parse.
 */
export type RecordedDecision = RecordedDecision_Serialize | RecordedDecision_Deserialize;

/**
 *  One recorded decision, as the registry lists it. `key` is the manifest's
 *  own spelling and is what revoke takes back, so even an entry a hand edit
 *  mangled can still be withdrawn; the typed fields are parsed from it for
 *  display and absent where it does not parse.
 */
export type RecordedDecision_Deserialize = {
	scope: Scope,
	key: string,
	kind: ItemKind | null,
	name: string,
	harness: HarnessId | null,
	record: DecisionRecord_Deserialize,
	state: RecordState,
};

/**
 *  One recorded decision, as the registry lists it. `key` is the manifest's
 *  own spelling and is what revoke takes back, so even an entry a hand edit
 *  mangled can still be withdrawn; the typed fields are parsed from it for
 *  display and absent where it does not parse.
 */
export type RecordedDecision_Serialize = {
	scope: Scope,
	key: string,
	kind: ItemKind | null,
	name: string,
	harness: HarnessId | null,
	record: DecisionRecord_Serialize,
	state: RecordState,
};

export type ReportRouteView = {
	kendexOwned: boolean,
	repo: string | null,
	label: string | null,
	/**  Prefilled new-issue page — only when the report belongs upstream. */
	issueUrl: string | null,
};

/**
 *  One recorded review. The key it is stored under is the installation:
 *  kind, name and harness, inside the scope whose manifest holds it.
 */
export type SafetyOverride = SafetyOverride_Serialize | SafetyOverride_Deserialize;

/**
 *  One recorded review. The key it is stored under is the installation:
 *  kind, name and harness, inside the scope whose manifest holds it.
 */
export type SafetyOverride_Deserialize = {
	/**
	 *  Hash of the complete bytes that were reviewed. Empty on a record
	 *  written before decisions bound to those bytes: such a record proves
	 *  nothing about what is installed now, so it reads as stale and the
	 *  content has to be reviewed again.
	 */
	"review-hash"?: string,
	/**  The rule set that produced the findings below. */
	ruleset: number,
	/**  Fingerprints of the exact findings that were reviewed, sorted. */
	findings: string[],
	"granted-at": string,
	note?: string | null,
};

/**
 *  One recorded review. The key it is stored under is the installation:
 *  kind, name and harness, inside the scope whose manifest holds it.
 */
export type SafetyOverride_Serialize = {
	/**
	 *  Hash of the complete bytes that were reviewed. Empty on a record
	 *  written before decisions bound to those bytes: such a record proves
	 *  nothing about what is installed now, so it reads as stale and the
	 *  content has to be reviewed again.
	 */
	"review-hash": string,
	/**  The rule set that produced the findings below. */
	ruleset: number,
	/**  Fingerprints of the exact findings that were reviewed, sorted. */
	findings: string[],
	"granted-at": string,
	note?: string | null,
};

/**
 *  Every dismissal for one installation, and the content they were made
 *  against. Stored under the installation's key: kind, name and harness.
 */
export type SafetyReview = SafetyReview_Serialize | SafetyReview_Deserialize;

/**
 *  Every dismissal for one installation, and the content they were made
 *  against. Stored under the installation's key: kind, name and harness.
 */
export type SafetyReview_Deserialize = {
	"review-hash": string,
	ruleset: number,
	dismissed?: { [key in string]: Dismissal_Deserialize },
};

/**
 *  Every dismissal for one installation, and the content they were made
 *  against. Stored under the installation's key: kind, name and harness.
 */
export type SafetyReview_Serialize = {
	"review-hash": string,
	ruleset: number,
	dismissed?: { [key in string]: Dismissal_Serialize },
};

export type SafetyScore = {
	score: number,
	deductions: Deduction[],
};

export type ScanResult = {
	harnesses: DetectedHarness[],
	items: ObservedItem[],
	/**  Registered projects whose directory is gone — flagged, never dropped. */
	missingProjects: string[],
	/**  Unreadable or unparsable surfaces; truth the scan could not reach. */
	warnings: string[],
};

export type Scope = { scope: "global" } | { scope: "project"; root: string };

export type ScopeError = {
	kind: ScopeErrorKind,
	message: string,
};

/**
 *  Why a scope couldn't be audited: a kind the UI can act on (retry, remove
 *  the project, show the file) plus the plain-words message underneath it.
 */
export type ScopeErrorKind = 
/**
 *  The lock exists but isn't readable as JSON, or as this build's lock
 *  shape — damaged, not merely old.
 */
"lock-corrupt" | 
/**  The manifest or lock was written by a newer kendex than this one. */
"schema-too-new" | 
/**  The manifest parses but fails validation. */
"manifest-invalid" | "other";

export type Severity = "low" | "medium" | "high" | "critical";

export type SkillsShHit = {
	/**  The skill's directory name inside its repository. */
	skill: string,
	/**  `owner/repo` — what an install actually subscribes to. */
	repo: string,
	installs: number,
};

/**  A rule that applies here but could not run, and why. */
export type SkippedRule = {
	rule: string,
	reason: string,
};

export type SourceDecl = SourceDecl_Serialize | SourceDecl_Deserialize;

export type SourceDecl_Deserialize = {
	repo: string | null,
	path: string | null,
	/**
	 *  Which revision of a remote to read. A full commit id is a pin: that
	 *  commit and no other, forever, and it works offline once cached. A
	 *  tag or branch tracks — every refresh re-resolves it and the new
	 *  content is previewed before anything is written. Absent tracks the
	 *  repository's default branch.
	 */
	rev: string | null,
	enabled?: boolean,
};

export type SourceDecl_Serialize = {
	repo?: string | null,
	path?: string | null,
	/**
	 *  Which revision of a remote to read. A full commit id is a pin: that
	 *  commit and no other, forever, and it works offline once cached. A
	 *  tag or branch tracks — every refresh re-resolves it and the new
	 *  content is previewed before anything is written. Absent tracks the
	 *  repository's default branch.
	 */
	rev?: string | null,
	enabled: boolean,
};

/**  Everything the Sources page shows for one declared source in one scope. */
export type SourceRow = {
	scope: Scope,
	name: string,
	reference: string,
	isRemote: boolean,
	enabled: boolean,
	/**  Cache HEAD for remotes — freshness display. */
	head: string | null,
	declaredItems: string[],
};

/**  One check finding shaped for a screen with an Open button. */
export type StatusFinding = {
	file: string,
	kind: string,
	name: string,
	pass: string,
	severity: string,
	message: string,
	fix: string,
};

/**  One row of GET /api/v1/submissions — what a Mine row polls. */
export type SubmissionRow = {
	repo: string,
	status: string,
	status_reason: string | null,
	head_commit: string | null,
	indexed_at: string | null,
};

export type SubmitPreflight = {
	row: MineRow,
	checks: PreflightCheck[],
	/**  The `owner/repo` a submit would send. */
	candidate: string | null,
	/**
	 *  Every locally-checkable row passes. The server still has the last
	 *  word on visibility and push authority.
	 */
	ready: boolean,
};

export type SubmittedView = {
	repo: string,
	status: string,
};

/**  What subscribing declared, after the plan ran. */
export type SubscribeOutcome = {
	name: string,
	/**  The declared repository or path. */
	reference: string,
	rev: string | null,
	/**
	 *  The package a tree or skills.sh URL was leading to — where the app
	 *  opens next, never an identity.
	 */
	lead: string | null,
	notes: string[],
};

/**
 *  The subscription a browsed repository already has on this machine, so
 *  the page can carry on as that subscription instead of a stranger.
 */
export type SubscriptionRef = {
	scope: Scope,
	source: string,
};

/**  The job an item helps with. */
export type Tag = 
/**  Reading code and saying what is wrong with it. */
"review" | 
/**  Writing, running, or reasoning about tests. */
"testing" | 
/**  Documentation, references, and explaining things in prose. */
"docs" | 
/**  Finding things out — sources, prior art, evidence. */
"research" | 
/**  Deciding what to build and in what order. */
"planning" | 
/**  Reshaping code that already works. */
"refactoring" | 
/**  Working out why something is broken. */
"debugging" | 
/**  Safety, secrets, permissions, and untrusted input. */
"security" | 
/**  Speed, memory, and the cost of running something. */
"performance" | 
/**  Version control — branches, history, worktrees, pull requests. */
"git" | 
/**  Compiling, packaging, versioning, and shipping a release. */
"release" | 
/**  Databases, schemas, migrations, and analysis. */
"data" | 
/**  Interfaces: layout, styling, design systems, accessibility. */
"ui" | 
/**  Talking to other services — APIs, webhooks, third-party tools. */
"integration" | 
/**  Driving other tools and agents, and the workflows that chain them. */
"automation";

/**
 *  Where warning starts and where installing stops. Configured in app
 *  settings rather than in a manifest: a manifest travels with the
 *  repository it describes, and a catalog that could lower the bar it is
 *  measured against is not being measured.
 */
export type Thresholds = {
	"warn-below": number,
	"block-below": number,
};

/**
 *  What unsubscribing from a marketplace would do: the packages that can be
 *  removed or kept as-is, the ones the user edited (which must be forked or
 *  discarded first), and the curated sets that leave with the source.
 */
export type UnsubscribePreview = {
	removable: PackageRef[],
	edited: PackageRef[],
	bundles: string[],
};

/**  One declared package's update standing. */
export type UpdateRow = {
	scope: Scope,
	kind: ItemKind,
	name: string,
	source: string,
	repo: string,
	/**
	 *  `repo` as [`crate::source_ref::repo_identity`] spells it — the one
	 *  identity two scopes' rows share when they name one repository two
	 *  ways, on any host.
	 */
	repoIdentity: string,
	/**  The content revision installed now, when the lock records it. */
	current: VersionRef | null,
	/**  The newest content revision the mirror knows. */
	latest: VersionRef | null,
	/**
	 *  The package's files changed between current and latest — a moved
	 *  repository that never touched this package is not an update.
	 */
	updateAvailable: boolean,
	/**
	 *  Held at a version — the effective installation graph's word, not
	 *  only the item's own `rev`: a pinned source, a pinned bundle, or a
	 *  pinned dependency parent all hold what they carry.
	 */
	pinned: boolean,
	/**  Who holds it, when `pinned`. */
	holdOwner: HoldOwner | null,
	/**  The user asked to stop hearing about this package's updates. */
	ignored: boolean,
	/**
	 *  The installed files were edited by hand; updating is blocked until
	 *  the edit is kept as a fork or discarded.
	 */
	blockedByLocalEdit: boolean,
	/**
	 *  Which renderings carry the edit, one entry per physical rendering:
	 *  an agent renders once per tool, while tools sharing a skill's
	 *  canonical tree count once. Keeping the edit as a fork captures one
	 *  rendering's bytes — it has to be the one that was changed.
	 */
	editedHarnesses: HarnessId[],
	/**
	 *  The edited rendering a fork can capture, when one exists — an
	 *  agent edited only in a tool whose format cannot be read back has
	 *  none, and the UI must not offer what the engine will refuse.
	 */
	forkableHarness: HarnessId | null,
	/**
	 *  Whether dropping the edits can put the currently resolved content
	 *  back in place, without moving any revision — the source content
	 *  resolved, whether or not its history could be read. False once the
	 *  source no longer carries the package.
	 */
	canDiscard: boolean,
	/**
	 *  Whether this place can move to the newest content on its own: the
	 *  newest is known, and the hold — if any — is this declaration's to
	 *  move rather than a bundle's or parent's.
	 */
	canTakeLatest: boolean,
	/**
	 *  Installed as a bundle member or a dependency, with no declaration
	 *  of its own: whatever pulled it in owns its revision, and a fork
	 *  needs a declaration to turn local.
	 */
	derived: boolean,
	/**  This package is a local fork of a catalog item. */
	forked: boolean,
	/**  Installations of this package disagree on their source commit. */
	mixed: boolean,
	/**  The source's tracked tip no longer carries this package at all. */
	removedUpstream: boolean,
};

/**
 *  Update standing for one scope, and every package the standing could not
 *  be computed for. The warnings are the report's honesty: a package whose
 *  mirror cannot be read is listed here, never silently shown as current.
 */
export type UpdatesReport = UpdatesReport_Serialize | UpdatesReport_Deserialize;

/**
 *  Update standing for one scope, and every package the standing could not
 *  be computed for. The warnings are the report's honesty: a package whose
 *  mirror cannot be read is listed here, never silently shown as current.
 */
export type UpdatesReport_Deserialize = {
	rows: UpdateRow[],
	warnings: ItemWarning_Deserialize[],
};

/**
 *  Update standing for one scope, and every package the standing could not
 *  be computed for. The warnings are the report's honesty: a package whose
 *  mirror cannot be read is listed here, never silently shown as current.
 */
export type UpdatesReport_Serialize = {
	rows: UpdateRow[],
	warnings: ItemWarning_Serialize[],
};

export type Verdict = 
/**  Nothing found worth saying. */
"clean" | 
/**  Findings worth reading before installing; the install proceeds. */
"warn" | 
/**  Nothing installs until a person reviews it. */
"block";

/**  One version a row points at. */
export type VersionRef = {
	commit: string,
	/**  Release name when a tag points at the commit. */
	label: string | null,
	date: string | null,
};

/**
 *  One version of a package: a commit that changed its files, wearing any
 *  tag names that point at it.
 */
export type VersionRow = {
	/**  Full commit id. */
	id: string,
	/**  The release name, when a tag points at this commit. */
	label: string | null,
	/**  ISO-8601 committer date. */
	date: string,
	summary: string,
	/**  This is the content revision the installed package holds. */
	installed: boolean,
	newerThanInstalled: boolean,
};

/**  One side of the comparison. */
export type VersionSel = 
/**  The package's source subtree at a commit. */
{ at: "commit"; commit: string } | 
/**  What is installed on disk right now. */
{ at: "installed" };

export type ZoomState = {
	/**
	 *  The size on screen. Every resize the window takes moves it, so a
	 *  page that has just reloaded reads what it is looking at.
	 */
	percent: number,
	/**
	 *  The window would not take the saved size when it opened, so
	 *  `percent` is the fallback and the saved size is not on screen. A
	 *  fact about the opening: a resize that works later moves the size but
	 *  does not make the opening have worked.
	 */
	launchRefused: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

