//! What a fork takes from an installed agent. The file on disk is a
//! generated document: reading it back as source form drops the tool
//! denies its harness stated, flips defaults the source never wrote, and
//! captures the do-not-edit banner into the body so the next render writes
//! a second one.

use std::fs;
use std::path::PathBuf;

use kendex_core::engine::desired::native_dir;
use kendex_core::error::CoreError;

use super::*;

const BANNER: &str = "> Generated by kendex — do not edit; regenerated on every refresh. Intent lives in kendex.toml.";

/// A world whose catalog carries the agent `rev`, declared on `harnesses`
/// and applied. `catalog` is the catalog's own control file, where a
/// publisher states per-harness frontmatter defaults; `project` is
/// whatever the scope's own manifest adds beneath the declaration.
#[allow(clippy::unwrap_used)]
fn agent_world(harnesses: &str, agent: &str, catalog: &str, project: &str) -> World {
    let w = world();
    let agents = w.upstream.join("agents");
    fs::create_dir_all(&agents).unwrap();
    fs::write(agents.join("rev.md"), agent).unwrap();
    fs::write(w.upstream.join("kendex.toml"), catalog).unwrap();
    commit(&w.upstream, "one");
    let path = manifest::manifest_path(&w.env, &w.scope);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(
        &path,
        format!(
            "schema = 6\n\n[sources.cat]\nrepo = \"{REPO}\"\n\n[install]\nharnesses = [{harnesses}]\nmethod = \"symlink\"\n\n[agents.rev]\nsource = \"cat\"\n\n{project}"
        ),
    )
    .unwrap();
    sync_and_apply(&w);
    w
}

/// The rendered agent's own path, taken from the environment rather than
/// composed, so a home reached through a link spells it the one way.
#[allow(clippy::unwrap_used)]
fn rendered(w: &World, harness: HarnessId, name: &str) -> PathBuf {
    native_dir(&w.env, &w.scope, harness, ItemKind::Agent)
        .unwrap()
        .join(format!("{name}.md"))
}

fn captured(w: &World, name: &str) -> PathBuf {
    w.home.join(format!("app/.kendex-local/agents/{name}.md"))
}

/// Replace the agent's prose where it stands, the way a person editing an
/// installed agent does, leaving every generated line alone.
#[allow(clippy::unwrap_used)]
fn edit_body(path: &std::path::Path) {
    let text = fs::read_to_string(path).unwrap();
    assert!(text.contains("Upstream body."), "{text}");
    fs::write(path, text.replace("Upstream body.", "My body.")).unwrap();
}

#[allow(clippy::unwrap_used)]
fn resettle(w: &World) {
    let report = audit(&w.env, &w.scope).unwrap();
    apply::execute(&w.env, &report.plan, None).unwrap();
}

fn deny_line(text: &str, key: &str) -> String {
    text.lines()
        .find(|line| line.starts_with(key))
        .unwrap_or_default()
        .to_owned()
}

fn banners(text: &str) -> usize {
    times(text, BANNER)
}

/// How many lines are exactly `line`. Every generated section is asserted
/// by count rather than presence: a section the capture kept and the next
/// render wrote again is present either way, so `contains` cannot tell a
/// carried configuration from a duplicated one.
fn times(text: &str, line: &str) -> usize {
    text.lines()
        .filter(|written| written.trim() == line)
        .count()
}

/// Claude states denies in `disallowedTools:`, a key the source form has
/// no spelling for. Captured from the rendering it is dropped on the way
/// back in, and the fork comes out able to run the tools the agent was
/// installed without.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_a_claude_agent_keeps_its_denies_its_allowlist_and_one_banner() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\ntools: Read, Grep\n---\nUpstream body.\n",
        "[agent-frontmatter.claude]\nrev = { deny-tools = [\"WebFetch\"] }\n",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    assert!(
        deny_line(&fs::read_to_string(&file).unwrap(), "disallowedTools:").contains("WebFetch")
    );
    edit_body(&file);

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let source = fs::read_to_string(captured(&w, "rev")).unwrap();
    assert!(
        source.contains("tools: Read, Grep") && source.contains("My body."),
        "the captured source is the publisher's frontmatter over the person's prose: {source}"
    );
    assert_eq!(banners(&source), 0, "{source}");

    let text = fs::read_to_string(&file).unwrap();
    assert!(
        deny_line(&text, "disallowedTools:").contains("WebFetch"),
        "the fork must not hand back a tool the installation denied: {text}"
    );
    assert!(text.contains("tools: Read, Grep"), "{text}");
    assert!(text.contains("My body."), "{text}");
    assert_eq!(banners(&text), 1, "{text}");
}

/// The catalog's frontmatter defaults are not harness-scoped to the
/// rendering a fork captures: keeping the Gemini copy has to carry
/// Claude's denies too, or the very next apply widens the copy the fork
/// never touched.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_a_gemini_agent_keeps_its_allowlist_and_the_other_tools_denies() {
    let w = agent_world(
        "\"claude\", \"gemini\"",
        "---\nname: rev\ndescription: agent rev\ntools: Read, Grep\n---\nUpstream body.\n",
        "[agent-frontmatter.claude]\nrev = { deny-tools = [\"WebFetch\"] }\n",
        "",
    );
    let file = rendered(&w, HarnessId::Gemini, "rev");
    edit_body(&file);

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Gemini).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let text = fs::read_to_string(&file).unwrap();
    assert!(
        text.contains("- read_file") && text.contains("- grep_search"),
        "the fork keeps Gemini's allowlist: {text}"
    );
    assert!(text.contains("My body."), "{text}");
    assert_eq!(banners(&text), 1, "{text}");

    let claude = fs::read_to_string(rendered(&w, HarnessId::Claude, "rev")).unwrap();
    assert!(
        deny_line(&claude, "disallowedTools:").contains("WebFetch"),
        "keeping the Gemini copy must not widen the Claude one: {claude}"
    );
    assert!(claude.contains("tools: Read, Grep"), "{claude}");
}

/// Pi states tool access as a deny list and nothing else, so everything
/// that restricts a Pi agent is in the key the source form cannot hold.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_a_pi_agent_keeps_its_deny_list_and_one_banner() {
    let w = agent_world(
        "\"pi\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "[agent-frontmatter.pi]\nrev = { deny-tools = [\"read_file\"] }\n",
        "",
    );
    let file = rendered(&w, HarnessId::Pi, "rev");
    assert!(deny_line(&fs::read_to_string(&file).unwrap(), "deny-tools:").contains("read_file"));
    edit_body(&file);

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Pi).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let text = fs::read_to_string(&file).unwrap();
    assert!(
        deny_line(&text, "deny-tools:").contains("read_file"),
        "the fork must not hand back a tool the installation denied: {text}"
    );
    assert!(text.contains("My body."), "{text}");
    assert_eq!(banners(&text), 1, "{text}");
}

/// Every manifest table an agent answers to is keyed by its installed
/// name. A copy under a new name reads none of them unless they come with
/// it, and the original — still declared from its source — has to keep
/// its own.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_beside_carries_the_projects_denies_without_taking_them() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "[agent-frontmatter.claude]\nrev = { deny-tools = [\"Bash\"] }\n\n[agent-launch-instructions]\nrev = \"Read the brief first.\"\n",
    );
    edit_body(&rendered(&w, HarnessId::Claude, "rev"));

    let plan = fork::fork_beside(
        &w.env,
        &w.scope,
        ItemKind::Agent,
        "rev",
        HarnessId::Claude,
        "rev-mine",
        None,
    )
    .unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let copy = fs::read_to_string(rendered(&w, HarnessId::Claude, "rev-mine")).unwrap();
    assert!(
        deny_line(&copy, "disallowedTools:").contains("Bash"),
        "the copy must not be more permissive than the agent it came from: {copy}"
    );
    assert!(copy.contains("Read the brief first."), "{copy}");
    assert!(copy.contains("My body."), "{copy}");

    let original = fs::read_to_string(rendered(&w, HarnessId::Claude, "rev")).unwrap();
    assert!(
        deny_line(&original, "disallowedTools:").contains("Bash"),
        "the original stays declared from its source and keeps its own denies: {original}"
    );
}

/// A rename is the same problem with the old name gone: the tables move
/// rather than being copied, and nothing is left keyed to a name no item
/// answers to.
#[test]
#[allow(clippy::unwrap_used)]
fn renaming_an_agent_fork_carries_its_denies_and_instructions() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "[agent-frontmatter.claude]\nrev = { deny-tools = [\"Bash\"] }\n\n[agent-launch-instructions]\nrev = \"Read the brief first.\"\n",
    );
    edit_body(&rendered(&w, HarnessId::Claude, "rev"));
    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let plan = fork::rename_fork(&w.env, &w.scope, ItemKind::Agent, "rev", "my-rev").unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let text = fs::read_to_string(rendered(&w, HarnessId::Claude, "my-rev")).unwrap();
    assert!(
        deny_line(&text, "disallowedTools:").contains("Bash"),
        "the renamed fork must not be more permissive than it was: {text}"
    );
    assert!(text.contains("Read the brief first."), "{text}");
    let recorded = manifest_text(&w);
    assert!(
        recorded.contains("[agent-frontmatter.claude.my-rev]")
            && recorded.contains("my-rev = \"Read the brief first.\""),
        "the settings and the instructions both move: {recorded}"
    );
    assert!(
        !recorded.contains("[agent-frontmatter.claude.rev]")
            && !recorded.contains("\nrev = \"Read the brief first.\""),
        "nothing stays keyed to a name no item answers to: {recorded}"
    );
}

/// A person who tightens a generated file by hand states something the
/// local source has no key for and the manifest is not being written from.
/// Forking anyway would hand them back the tools they took away, so the
/// fork refuses and writes nothing.
#[test]
#[allow(clippy::unwrap_used)]
fn a_hand_tightened_deny_refuses_the_fork_and_writes_nothing() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace(
            "disallowedTools: Agent, AskUserQuestion",
            "disallowedTools: Agent, AskUserQuestion, Bash, WebFetch",
        ),
    )
    .unwrap();

    let refused =
        fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap_err();
    let said = refused.to_string();
    assert!(
        matches!(refused, CoreError::ForkWidensAccess { .. }),
        "{refused:?}"
    );
    assert!(
        said.contains("Bash") && said.contains("WebFetch") && said.contains("nothing was written"),
        "the refusal names what it stopped on: {said}"
    );
    assert!(!captured(&w, "rev").exists(), "nothing was written");
    assert!(!manifest_text(&w).contains("[forks.agent.rev]"));
}

/// The same refusal from the other direction: an allowlist added by hand
/// to a file that stated none. What the fork would give back is every
/// tool outside it, so the refusal names the allowlist instead.
#[test]
#[allow(clippy::unwrap_used)]
fn a_hand_added_allowlist_refuses_the_fork() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace("disallowedTools:", "tools: Read, Grep\ndisallowedTools:"),
    )
    .unwrap();

    let refused =
        fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap_err();
    let said = refused.to_string();
    assert!(
        matches!(refused, CoreError::ForkWidensAccess { .. }),
        "{refused:?}"
    );
    assert!(said.contains("Read, Grep"), "{said}");
    assert!(!captured(&w, "rev").exists(), "nothing was written");
}

/// A fork of an agent nobody tightened by hand goes through: the ordinary
/// path stays ordinary, and an edit to the prose alone is not a permission
/// question.
#[test]
#[allow(clippy::unwrap_used)]
fn an_ordinary_agent_still_forks() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    edit_body(&rendered(&w, HarnessId::Claude, "rev"));
    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);
    assert!(
        fs::read_to_string(rendered(&w, HarnessId::Claude, "rev"))
            .unwrap()
            .contains("My body.")
    );
    assert!(audit(&w.env, &w.scope).unwrap().drift.is_empty());
}

/// Frontmatter that will not parse is not the same answer as frontmatter
/// stating nothing. What the person took away cannot be read, so it cannot
/// be proven carried either, and the fork refuses rather than guess.
#[test]
#[allow(clippy::unwrap_used)]
fn an_unreadable_frontmatter_refuses_the_fork() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace(
            "disallowedTools:",
            "tools: Read\ntools: Grep\ndisallowedTools:",
        ),
    )
    .unwrap();

    let refused =
        fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap_err();
    assert!(
        matches!(refused, CoreError::ForkWidensAccess { .. }),
        "{refused:?}"
    );
    assert!(refused.to_string().contains("cannot be read"), "{refused}");
    assert!(!captured(&w, "rev").exists(), "nothing was written");
}

/// A person who changes a setting in the generated file changed something
/// the override table has a field for. Those ride into the manifest rather
/// than being dropped, so the set a fork loses is only what nothing can
/// hold: `description:` and `tags:`, which the table has no field for.
#[test]
#[allow(clippy::unwrap_used)]
fn a_settings_edit_rides_into_the_manifest_and_a_description_edit_does_not() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\ncolor: blue\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace("color: blue", "color: magenta")
            .replace("background: true", "background: false")
            .replace("description: \"agent rev\"", "description: \"my rev\""),
    )
    .unwrap();

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let recorded = manifest_text(&w);
    assert!(
        recorded.contains("[agent-frontmatter.claude.rev]"),
        "the settings the person changed ride as overrides: {recorded}"
    );
    let settled = fs::read_to_string(&file).unwrap();
    assert!(settled.contains("color: magenta"), "{settled}");
    assert!(settled.contains("background: false"), "{settled}");
    assert!(
        settled.contains("description: \"agent rev\""),
        "a description edit has no override field and comes back from the publisher: {settled}"
    );
}

/// A hook scoped to one agent by name reaches the copy only if its
/// selector says so, and after a rename it points at a name nothing
/// answers to. Either way an agent-scoped PreToolUse restriction quietly
/// stops applying, which is this issue's own defect in the one table the
/// first round did not move.
#[test]
#[allow(clippy::unwrap_used)]
fn an_agent_scoped_hook_reaches_the_copy_and_follows_a_rename() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "[[custom-hooks]]\nevent = \"PreToolUse\"\nmatcher = \"Bash\"\ncommand = \"./guard.sh\"\nagents = \"rev\"\n",
    );
    let guarded = |name: &str| {
        fs::read_to_string(rendered(&w, HarnessId::Claude, name))
            .unwrap()
            .contains("./guard.sh")
    };
    assert!(
        guarded("rev"),
        "the hook reaches the original to begin with"
    );
    edit_body(&rendered(&w, HarnessId::Claude, "rev"));

    let plan = fork::fork_beside(
        &w.env,
        &w.scope,
        ItemKind::Agent,
        "rev",
        HarnessId::Claude,
        "rev-mine",
        None,
    )
    .unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);
    assert!(
        guarded("rev-mine"),
        "the copy must not escape the hook the agent it came from runs under"
    );
    assert!(guarded("rev"), "and the original keeps it");

    let plan =
        fork::rename_fork(&w.env, &w.scope, ItemKind::Agent, "rev-mine", "rev-ours").unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);
    assert!(guarded("rev-ours"), "the hook follows the rename");
    let recorded = manifest_text(&w);
    assert!(
        !recorded.contains("rev-mine"),
        "nothing stays selected by a name no agent answers to: {recorded}"
    );
}

/// Forking a skill beside its source must not touch an agent's settings.
/// The manifest keys agents and skills in separate tables but one shared
/// namespace of names, so an unguarded rekey copies the settings of an
/// agent that merely shares the skill's name.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_a_skill_beside_leaves_a_same_named_agents_settings_alone() {
    let w = world();
    write_skill(&w.upstream, "rev", "Upstream skill.");
    let agents = w.upstream.join("agents");
    fs::create_dir_all(&agents).unwrap();
    fs::write(
        agents.join("rev.md"),
        "---\nname: rev\ndescription: agent rev\n---\nAgent body.\n",
    )
    .unwrap();
    commit(&w.upstream, "one");
    declare(
        &w,
        "[skills.rev]\nsource = \"cat\"\n\n[agents.rev]\nsource = \"cat\"\n\n[agent-frontmatter.claude]\nrev = { deny-tools = [\"Bash\"] }\n",
    );
    sync_and_apply(&w);
    fs::write(
        w.home.join("app/.agents/skills/rev/SKILL.md"),
        "---\nname: rev\ndescription: mine\n---\nMy skill.\n",
    )
    .unwrap();

    let plan = fork::fork_beside(
        &w.env,
        &w.scope,
        ItemKind::Skill,
        "rev",
        HarnessId::Claude,
        "rev-mine",
        None,
    )
    .unwrap();
    apply::execute(&w.env, &plan, None).unwrap();

    let recorded = manifest_text(&w);
    assert!(
        !recorded.contains("agent-frontmatter.claude.rev-mine"),
        "a skill fork must not copy an agent's settings onto its new name: {recorded}"
    );
}

/// A name already carrying an agent's settings is not free for a copy to
/// land on. Writing the copy's own settings under it would replace what
/// the person wrote, and merging the two would invent a policy nobody
/// asked for, so the fork refuses the way it refuses every other thing it
/// cannot carry.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_beside_refuses_a_name_that_already_carries_settings() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "[agent-frontmatter.claude]\nrev-mine = { deny-tools = [\"Bash\"] }\n",
    );
    edit_body(&rendered(&w, HarnessId::Claude, "rev"));

    let refused = fork::fork_beside(
        &w.env,
        &w.scope,
        ItemKind::Agent,
        "rev",
        HarnessId::Claude,
        "rev-mine",
        None,
    )
    .unwrap_err();
    assert!(
        matches!(refused, CoreError::ForkNameUnusable { .. }),
        "{refused:?}"
    );
    assert!(
        refused.to_string().contains("agent-frontmatter"),
        "the refusal names where the settings are: {refused}"
    );
    assert!(!captured(&w, "rev-mine").exists(), "nothing was written");
}

/// The generated sections are written again by the next render out of the
/// manifest entries this fork carries, so prose that kept a copy of them
/// renders twice. The banner was the first of these; the instructions and
/// the skills prose are the rest.
#[test]
#[allow(clippy::unwrap_used)]
fn the_generated_sections_are_written_once_after_a_fork() {
    let w = world();
    write_skill(&w.upstream, "recon", "Recon.");
    let agents = w.upstream.join("agents");
    fs::create_dir_all(&agents).unwrap();
    fs::write(
        agents.join("rev.md"),
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
    )
    .unwrap();
    fs::write(
        w.upstream.join("kendex.toml"),
        "[agent-skills]\nrev = [\"recon\"]\n",
    )
    .unwrap();
    commit(&w.upstream, "one");
    let path = manifest::manifest_path(&w.env, &w.scope);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(
        &path,
        format!(
            "schema = 6\n\n[sources.cat]\nrepo = \"{REPO}\"\n\n[install]\nharnesses = [\"gemini\"]\nmethod = \"symlink\"\n\n[agents.rev]\nsource = \"cat\"\n\n[skills.recon]\nsource = \"cat\"\n\n[agent-launch-instructions]\nrev = \"Read the brief first.\"\n\n[agent-additional-instructions]\nrev = \"Say what you changed.\"\n"
        ),
    )
    .unwrap();
    sync_and_apply(&w);
    let file = rendered(&w, HarnessId::Gemini, "rev");
    let before = fs::read_to_string(&file).unwrap();
    assert_eq!(times(&before, "## Required Skills"), 1, "{before}");
    edit_body(&file);

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Gemini).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let source = fs::read_to_string(captured(&w, "rev")).unwrap();
    for section in [
        "## Launch Instructions",
        "## Additional Instructions",
        "## Required Skills",
    ] {
        assert_eq!(
            times(&source, section),
            0,
            "the captured prose must not carry {section}, which the render writes: {source}"
        );
    }
    assert!(source.contains("My body."), "{source}");

    // The instruction sections are keyed by the agent's name, so the fork
    // still renders both and each must appear exactly once. A skills
    // section is not asserted here: a local agent's skill list is filtered
    // to its own source, so a catalog skill leaves the rendering after any
    // fork for reasons older than this change.
    let text = fs::read_to_string(&file).unwrap();
    for section in ["## Launch Instructions", "## Additional Instructions"] {
        assert_eq!(times(&text, section), 1, "{section} rendered twice: {text}");
    }
    assert_eq!(banners(&text), 1, "{text}");
    assert_eq!(times(&text, "My body."), 1, "{text}");
}

/// Deleting a rendered key is an edit in the restrictive direction, and
/// the fork must not answer it by putting the publisher's value back. An
/// override states what a value is and never that there is none, so only
/// an effort can be cleared; everything else refuses, naming what was
/// deleted.
#[test]
#[allow(clippy::unwrap_used)]
fn a_deleted_setting_is_carried_where_it_can_be_and_refused_where_it_cannot() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\nmodel: sonnet\neffort: high\ncolor: blue\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let rendering = fs::read_to_string(&file).unwrap();
    assert!(rendering.contains("effort: high") && rendering.contains("color: blue"));

    // An effort can be cleared: every renderer reads `none` as no effort.
    let without_effort: String = rendering
        .lines()
        .filter(|line| !line.starts_with("effort:"))
        .map(|line| format!("{line}\n"))
        .collect();
    fs::write(&file, &without_effort).unwrap();
    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);
    let settled = fs::read_to_string(&file).unwrap();
    assert!(
        !settled.lines().any(|line| line.starts_with("effort:")),
        "a cleared effort must not come back: {settled}"
    );

    // A colour cannot: nothing in the override table says there is none.
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\ncolor: blue\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let rendering = fs::read_to_string(&file).unwrap();
    let without_color: String = rendering
        .lines()
        .filter(|line| !line.starts_with("color:"))
        .map(|line| format!("{line}\n"))
        .collect();
    fs::write(&file, &without_color).unwrap();
    let refused =
        fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap_err();
    assert!(
        matches!(refused, CoreError::ForkWidensAccess { .. }),
        "{refused:?}"
    );
    assert!(
        refused.to_string().contains("deleted") && refused.to_string().contains("color"),
        "the refusal names the deleted setting: {refused}"
    );
    assert!(!captured(&w, "rev").exists(), "nothing was written");
}

/// The capture takes the person's prose byte for byte. An indented code
/// block on the first line is content, not padding, and trimming it would
/// render the block as ordinary prose.
#[test]
#[allow(clippy::unwrap_used)]
fn an_indented_first_line_keeps_its_indentation() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace("Upstream body.", "    cargo run --release"),
    )
    .unwrap();

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let source = fs::read_to_string(captured(&w, "rev")).unwrap();
    assert!(
        source.contains("\n    cargo run --release"),
        "the code block lost its indentation: {source:?}"
    );
}
