//! What a fork takes from an installed agent. The file on disk is a
//! generated document: reading it back as source form drops the tool
//! denies its harness stated, flips defaults the source never wrote, and
//! captures the do-not-edit banner into the body so the next render writes
//! a second one.

use std::fs;
use std::path::PathBuf;

use kendex_core::engine::desired::native_dir;
use kendex_core::error::CoreError;

use super::*;

const BANNER: &str = "> Generated by kendex — do not edit; regenerated on every refresh. Intent lives in kendex.toml.";

/// A world whose catalog carries the agent `rev`, declared on `harnesses`
/// and applied. `catalog` is the catalog's own control file, where a
/// publisher states per-harness frontmatter defaults; `project` is
/// whatever the scope's own manifest adds beneath the declaration.
#[allow(clippy::unwrap_used)]
fn agent_world(harnesses: &str, agent: &str, catalog: &str, project: &str) -> World {
    let w = world();
    let agents = w.upstream.join("agents");
    fs::create_dir_all(&agents).unwrap();
    fs::write(agents.join("rev.md"), agent).unwrap();
    fs::write(w.upstream.join("kendex.toml"), catalog).unwrap();
    commit(&w.upstream, "one");
    let path = manifest::manifest_path(&w.env, &w.scope);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(
        &path,
        format!(
            "schema = 6\n\n[sources.cat]\nrepo = \"{REPO}\"\n\n[install]\nharnesses = [{harnesses}]\nmethod = \"symlink\"\n\n[agents.rev]\nsource = \"cat\"\n\n{project}"
        ),
    )
    .unwrap();
    sync_and_apply(&w);
    w
}

/// The rendered agent's own path, taken from the environment rather than
/// composed, so a home reached through a link spells it the one way.
#[allow(clippy::unwrap_used)]
fn rendered(w: &World, harness: HarnessId, name: &str) -> PathBuf {
    native_dir(&w.env, &w.scope, harness, ItemKind::Agent)
        .unwrap()
        .join(format!("{name}.md"))
}

fn captured(w: &World, name: &str) -> PathBuf {
    w.home.join(format!("app/.kendex-local/agents/{name}.md"))
}

/// Replace the agent's prose where it stands, the way a person editing an
/// installed agent does, leaving every generated line alone.
#[allow(clippy::unwrap_used)]
fn edit_body(path: &std::path::Path) {
    let text = fs::read_to_string(path).unwrap();
    assert!(text.contains("Upstream body."), "{text}");
    fs::write(path, text.replace("Upstream body.", "My body.")).unwrap();
}

#[allow(clippy::unwrap_used)]
fn resettle(w: &World) {
    let report = audit(&w.env, &w.scope).unwrap();
    apply::execute(&w.env, &report.plan, None).unwrap();
}

fn deny_line(text: &str, key: &str) -> String {
    text.lines()
        .find(|line| line.starts_with(key))
        .unwrap_or_default()
        .to_owned()
}

fn banners(text: &str) -> usize {
    text.lines().filter(|line| line.trim() == BANNER).count()
}

/// Claude states denies in `disallowedTools:`, a key the source form has
/// no spelling for. Captured from the rendering it is dropped on the way
/// back in, and the fork comes out able to run the tools the agent was
/// installed without.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_a_claude_agent_keeps_its_denies_its_allowlist_and_one_banner() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\ntools: Read, Grep\n---\nUpstream body.\n",
        "[agent-frontmatter.claude]\nrev = { deny-tools = [\"WebFetch\"] }\n",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    assert!(
        deny_line(&fs::read_to_string(&file).unwrap(), "disallowedTools:").contains("WebFetch")
    );
    edit_body(&file);

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let source = fs::read_to_string(captured(&w, "rev")).unwrap();
    assert!(
        source.contains("tools: Read, Grep") && source.contains("My body."),
        "the captured source is the publisher's frontmatter over the person's prose: {source}"
    );
    assert_eq!(banners(&source), 0, "{source}");

    let text = fs::read_to_string(&file).unwrap();
    assert!(
        deny_line(&text, "disallowedTools:").contains("WebFetch"),
        "the fork must not hand back a tool the installation denied: {text}"
    );
    assert!(text.contains("tools: Read, Grep"), "{text}");
    assert!(text.contains("My body."), "{text}");
    assert_eq!(banners(&text), 1, "{text}");
}

/// The catalog's frontmatter defaults are not harness-scoped to the
/// rendering a fork captures: keeping the Gemini copy has to carry
/// Claude's denies too, or the very next apply widens the copy the fork
/// never touched.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_a_gemini_agent_keeps_its_allowlist_and_the_other_tools_denies() {
    let w = agent_world(
        "\"claude\", \"gemini\"",
        "---\nname: rev\ndescription: agent rev\ntools: Read, Grep\n---\nUpstream body.\n",
        "[agent-frontmatter.claude]\nrev = { deny-tools = [\"WebFetch\"] }\n",
        "",
    );
    let file = rendered(&w, HarnessId::Gemini, "rev");
    edit_body(&file);

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Gemini).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let text = fs::read_to_string(&file).unwrap();
    assert!(
        text.contains("- read_file") && text.contains("- grep_search"),
        "the fork keeps Gemini's allowlist: {text}"
    );
    assert!(text.contains("My body."), "{text}");
    assert_eq!(banners(&text), 1, "{text}");

    let claude = fs::read_to_string(rendered(&w, HarnessId::Claude, "rev")).unwrap();
    assert!(
        deny_line(&claude, "disallowedTools:").contains("WebFetch"),
        "keeping the Gemini copy must not widen the Claude one: {claude}"
    );
    assert!(claude.contains("tools: Read, Grep"), "{claude}");
}

/// Pi states tool access as a deny list and nothing else, so everything
/// that restricts a Pi agent is in the key the source form cannot hold.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_a_pi_agent_keeps_its_deny_list_and_one_banner() {
    let w = agent_world(
        "\"pi\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "[agent-frontmatter.pi]\nrev = { deny-tools = [\"read_file\"] }\n",
        "",
    );
    let file = rendered(&w, HarnessId::Pi, "rev");
    assert!(deny_line(&fs::read_to_string(&file).unwrap(), "deny-tools:").contains("read_file"));
    edit_body(&file);

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Pi).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let text = fs::read_to_string(&file).unwrap();
    assert!(
        deny_line(&text, "deny-tools:").contains("read_file"),
        "the fork must not hand back a tool the installation denied: {text}"
    );
    assert!(text.contains("My body."), "{text}");
    assert_eq!(banners(&text), 1, "{text}");
}

/// Every manifest table an agent answers to is keyed by its installed
/// name. A copy under a new name reads none of them unless they come with
/// it, and the original — still declared from its source — has to keep
/// its own.
#[test]
#[allow(clippy::unwrap_used)]
fn forking_beside_carries_the_projects_denies_without_taking_them() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "[agent-frontmatter.claude]\nrev = { deny-tools = [\"Bash\"] }\n\n[agent-launch-instructions]\nrev = \"Read the brief first.\"\n",
    );
    edit_body(&rendered(&w, HarnessId::Claude, "rev"));

    let plan = fork::fork_beside(
        &w.env,
        &w.scope,
        ItemKind::Agent,
        "rev",
        HarnessId::Claude,
        "rev-mine",
        None,
    )
    .unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let copy = fs::read_to_string(rendered(&w, HarnessId::Claude, "rev-mine")).unwrap();
    assert!(
        deny_line(&copy, "disallowedTools:").contains("Bash"),
        "the copy must not be more permissive than the agent it came from: {copy}"
    );
    assert!(copy.contains("Read the brief first."), "{copy}");
    assert!(copy.contains("My body."), "{copy}");

    let original = fs::read_to_string(rendered(&w, HarnessId::Claude, "rev")).unwrap();
    assert!(
        deny_line(&original, "disallowedTools:").contains("Bash"),
        "the original stays declared from its source and keeps its own denies: {original}"
    );
}

/// A rename is the same problem with the old name gone: the tables move
/// rather than being copied, and nothing is left keyed to a name no item
/// answers to.
#[test]
#[allow(clippy::unwrap_used)]
fn renaming_an_agent_fork_carries_its_denies_and_instructions() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "[agent-frontmatter.claude]\nrev = { deny-tools = [\"Bash\"] }\n\n[agent-launch-instructions]\nrev = \"Read the brief first.\"\n",
    );
    edit_body(&rendered(&w, HarnessId::Claude, "rev"));
    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let plan = fork::rename_fork(&w.env, &w.scope, ItemKind::Agent, "rev", "my-rev").unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let text = fs::read_to_string(rendered(&w, HarnessId::Claude, "my-rev")).unwrap();
    assert!(
        deny_line(&text, "disallowedTools:").contains("Bash"),
        "the renamed fork must not be more permissive than it was: {text}"
    );
    assert!(text.contains("Read the brief first."), "{text}");
    let recorded = manifest_text(&w);
    assert!(recorded.contains("my-rev = "), "{recorded}");
    assert!(
        !recorded.contains("\nrev = "),
        "nothing stays keyed to a name no item answers to: {recorded}"
    );
}

/// A person who tightens a generated file by hand states something the
/// local source has no key for and the manifest is not being written from.
/// Forking anyway would hand them back the tools they took away, so the
/// fork refuses and writes nothing.
#[test]
#[allow(clippy::unwrap_used)]
fn a_hand_tightened_deny_refuses_the_fork_and_writes_nothing() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace(
            "disallowedTools: Agent, AskUserQuestion",
            "disallowedTools: Agent, AskUserQuestion, Bash, WebFetch",
        ),
    )
    .unwrap();

    let refused =
        fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap_err();
    let said = refused.to_string();
    assert!(
        matches!(refused, CoreError::ForkWidensAccess { .. }),
        "{refused:?}"
    );
    assert!(
        said.contains("Bash") && said.contains("WebFetch") && said.contains("nothing was written"),
        "the refusal names what it stopped on: {said}"
    );
    assert!(!captured(&w, "rev").exists(), "nothing was written");
    assert!(!manifest_text(&w).contains("[forks.agent.rev]"));
}

/// The same refusal from the other direction: an allowlist added by hand
/// to a file that stated none. What the fork would give back is every
/// tool outside it, so the refusal names the allowlist instead.
#[test]
#[allow(clippy::unwrap_used)]
fn a_hand_added_allowlist_refuses_the_fork() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace("disallowedTools:", "tools: Read, Grep\ndisallowedTools:"),
    )
    .unwrap();

    let refused =
        fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap_err();
    let said = refused.to_string();
    assert!(
        matches!(refused, CoreError::ForkWidensAccess { .. }),
        "{refused:?}"
    );
    assert!(said.contains("Read, Grep"), "{said}");
    assert!(!captured(&w, "rev").exists(), "nothing was written");
}

/// A fork of an agent nobody tightened by hand goes through: the ordinary
/// path stays ordinary, and an edit to the prose alone is not a permission
/// question.
#[test]
#[allow(clippy::unwrap_used)]
fn an_ordinary_agent_still_forks() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    edit_body(&rendered(&w, HarnessId::Claude, "rev"));
    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);
    assert!(
        fs::read_to_string(rendered(&w, HarnessId::Claude, "rev"))
            .unwrap()
            .contains("My body.")
    );
    assert!(audit(&w.env, &w.scope).unwrap().drift.is_empty());
}

/// Frontmatter that will not parse is not the same answer as frontmatter
/// stating nothing. What the person took away cannot be read, so it cannot
/// be proven carried either, and the fork refuses rather than guess.
#[test]
#[allow(clippy::unwrap_used)]
fn an_unreadable_frontmatter_refuses_the_fork() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace(
            "disallowedTools:",
            "tools: Read\ntools: Grep\ndisallowedTools:",
        ),
    )
    .unwrap();

    let refused =
        fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap_err();
    assert!(
        matches!(refused, CoreError::ForkWidensAccess { .. }),
        "{refused:?}"
    );
    assert!(refused.to_string().contains("cannot be read"), "{refused}");
    assert!(!captured(&w, "rev").exists(), "nothing was written");
}

/// A person who changes a setting in the generated file changed something
/// the override table has a field for. Those ride into the manifest rather
/// than being dropped, so the set a fork loses is only what nothing can
/// hold: `description:` and `tags:`, which the table has no field for.
#[test]
#[allow(clippy::unwrap_used)]
fn a_settings_edit_rides_into_the_manifest_and_a_description_edit_does_not() {
    let w = agent_world(
        "\"claude\"",
        "---\nname: rev\ndescription: agent rev\ncolor: blue\n---\nUpstream body.\n",
        "",
        "",
    );
    let file = rendered(&w, HarnessId::Claude, "rev");
    let text = fs::read_to_string(&file).unwrap();
    fs::write(
        &file,
        text.replace("color: blue", "color: magenta")
            .replace("background: true", "background: false")
            .replace("description: \"agent rev\"", "description: \"my rev\""),
    )
    .unwrap();

    let plan = fork::fork(&w.env, &w.scope, ItemKind::Agent, "rev", HarnessId::Claude).unwrap();
    apply::execute(&w.env, &plan, None).unwrap();
    resettle(&w);

    let recorded = manifest_text(&w);
    assert!(
        recorded.contains("[agent-frontmatter.claude.rev]"),
        "the settings the person changed ride as overrides: {recorded}"
    );
    let settled = fs::read_to_string(&file).unwrap();
    assert!(settled.contains("color: magenta"), "{settled}");
    assert!(settled.contains("background: false"), "{settled}");
    assert!(
        settled.contains("description: \"agent rev\""),
        "a description edit has no override field and comes back from the publisher: {settled}"
    );
}
