// Generated by pi-extensions/pi-root-policy.mjs; do not edit.
import { homedir } from "node:os"; import { posix, win32 } from "node:path";
export function piGlobalRoot(value=process.env.PI_CODING_AGENT_DIR, home=homedir(), platform=process.platform === "win32" ? "win32" : "posix") {
	const p=platform === "win32" ? win32 : posix, raw=value?.trim(), path=raw === "~" ? home : raw?.startsWith("~/") ? p.join(home, raw.slice(2)) : raw, absolute=platform === "win32" ? (/^[A-Za-z]:[\\/]/.test(path ?? "") || /^(?:\\\\|\/\/)[^\\/]+[\\/][^\\/]+(?:[\\/]|$)/.test(path ?? "")) : path?.startsWith("/");
	return absolute ? p.resolve(path) : p.resolve(home, ".pi", "agent"); }
