// Generated by pi-extensions/pi-root-policy.mjs; do not edit.
import { statSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, posix, resolve, win32 } from "node:path";

export type PiPathPlatform = "posix" | "win32";

export const PI_PROJECT_MARKER_DIRS = [
	".claude",
	".codex",
	".opencode",
	".cursor",
	".pi",
	".agents",
	".gemini",
] as const;

function platformPath(platform: PiPathPlatform) {
	return platform === "win32" ? win32 : posix;
}

export function piRootIsAbsolute(value: string, platform: PiPathPlatform): boolean {
	if (platform === "posix") return value.startsWith("/");
	if (/^[A-Za-z]:[\\/]/.test(value)) return true;
	return /^(?:\\\\|\/\/)[^\\/]+[\\/][^\\/]+(?:[\\/]|$)/.test(value);
}

function expandTilde(value: string, home: string, platform: PiPathPlatform): string {
	const paths = platformPath(platform);
	if (value === "~") return home;
	if (value.startsWith("~/")) return paths.join(home, value.slice(2));
	return value;
}

export function piGlobalRoot(
	value: string | undefined = process.env.PI_CODING_AGENT_DIR,
	home: string = homedir(),
	platform: PiPathPlatform = process.platform === "win32" ? "win32" : "posix",
): string {
	const paths = platformPath(platform);
	const configured = value?.trim();
	if (!configured) return paths.resolve(home, ".pi", "agent");
	const expanded = expandTilde(configured, home, platform);
	return piRootIsAbsolute(expanded, platform) ? paths.resolve(expanded) : paths.resolve(home, ".pi", "agent");
}

function isDirectory(path: string): boolean {
	try { return statSync(path).isDirectory(); } catch { return false; }
}

function isFile(path: string): boolean {
	try { return statSync(path).isFile(); } catch { return false; }
}

export function piProjectRoot(cwd: string, home: string = homedir()): string | undefined {
	let current = resolve(cwd);
	const stop = resolve(home);
	while (true) {
		if (isFile(join(current, ".kendex-lock.json"))) return current;
		if (current !== stop && PI_PROJECT_MARKER_DIRS.some((marker) => isDirectory(join(current, marker)))) return current;
		const parent = dirname(current);
		if (parent === current) return undefined;
		current = parent;
	}
}
