use crate::manifest::{CustomHook, FrontmatterOverrides, HookAgents, Manifest};
use crate::model::{HarnessId, ItemKind, Scope};

use super::permission::PermissionIntent;

pub mod claude;
pub mod codex;
pub mod copilot;
pub mod cursor;
pub mod gemini;
pub mod opencode;
pub mod pi;
mod source;

pub use source::{Role, SourceAgent, default_pane, parse_source_agent};

/// Everything a per-harness generator needs, already merged. `permissions`
/// is the effective intent — source `tools:` narrowed by manifest overrides;
/// renderers read it, never `overrides.deny_tools` directly.
#[derive(Clone)]
pub struct EffectiveAgent<'a> {
    pub source: &'a SourceAgent,
    pub harness: HarnessId,
    pub scope: &'a Scope,
    pub skills: Vec<String>,
    pub overrides: FrontmatterOverrides,
    pub permissions: PermissionIntent,
    pub launch_instructions: Option<String>,
    pub additional_instructions: Option<String>,
    pub custom_hooks: Vec<&'a CustomHook>,
}

pub const SHARED_START: &str = "<!-- kendex:shared-instructions:start -->";
pub const SHARED_END: &str = "<!-- kendex:shared-instructions:end -->";

/// Shared (`all`/`*`) text renders first inside strippable markers, then the
/// agent-specific text.
pub fn merged_instructions(
    table: &std::collections::BTreeMap<String, String>,
    agent_name: &str,
) -> Option<String> {
    let shared = table.get("all").or_else(|| table.get("*"));
    let specific = table.get(agent_name);
    match (shared, specific) {
        (None, None) => None,
        (None, Some(text)) => Some(text.clone()),
        (Some(shared), specific) => {
            let mut out = format!("{SHARED_START}\n{shared}\n{SHARED_END}");
            if let Some(text) = specific {
                out.push_str("\n\n");
                out.push_str(text);
            }
            Some(out)
        }
    }
}

/// Project overrides win per field over source-side defaults, except
/// deny-tools, which merge (v1 semantics).
pub fn merge_overrides(
    source_defaults: Option<&FrontmatterOverrides>,
    project: Option<&FrontmatterOverrides>,
) -> FrontmatterOverrides {
    let mut merged = source_defaults.cloned().unwrap_or_default();
    let Some(project) = project else {
        return merged;
    };
    macro_rules! take {
        ($field:ident) => {
            if project.$field.is_some() {
                merged.$field = project.$field.clone();
            }
        };
    }
    take!(color);
    take!(model);
    take!(allow_tools);
    take!(allowed_subagents);
    take!(pane);
    take!(background);
    take!(effort);
    take!(isolation);
    take!(memory);
    take!(mode);
    take!(sandbox_mode);
    take!(model_reasoning_effort);
    take!(nickname_candidates);
    match (&mut merged.deny_tools, &project.deny_tools) {
        (Some(base), Some(extra)) => {
            for tool in extra {
                if !base.contains(tool) {
                    base.push(tool.clone());
                }
            }
        }
        (None, Some(extra)) => merged.deny_tools = Some(extra.clone()),
        _ => {}
    }
    merged
}

/// The custom hooks one agent file carries on one harness: the ones whose
/// selector matches this agent, minus every hook `delivery()` sends through
/// a real registration instead — writing those here too would keep a second,
/// weaker copy of the same rule.
pub fn hooks_for_agent<'a>(
    env: &crate::env::Env,
    scope: &Scope,
    harness: HarnessId,
    manifest: &'a Manifest,
    agent: &SourceAgent,
) -> Vec<&'a CustomHook> {
    use crate::hook::{Delivery, HookSpec, delivery};
    let role = agent.role.map(Role::name);
    let names = crate::hook::custom_hook_names(manifest);
    manifest
        .custom_hooks
        .iter()
        .zip(names)
        .filter(|(hook, _)| {
            hook.enabled
                && match &hook.agents {
                    HookAgents::One(sel) => {
                        sel == "all" || Some(sel.as_str()) == role || sel == &agent.name
                    }
                    HookAgents::Many(list) => list
                        .iter()
                        .any(|sel| sel == &agent.name || Some(sel.as_str()) == role),
                }
        })
        .filter(|(hook, name)| {
            let spec = HookSpec::custom(hook, name.clone());
            spec.applies_to(harness)
                && matches!(
                    delivery(env, scope, harness, &spec),
                    Delivery::InAgentFile | Delivery::Advisory
                )
        })
        .map(|(hook, _)| hook)
        .collect()
}

/// The generated-file banner every harness variant includes.
pub const GENERATED_BANNER: &str = "> Generated by kendex — do not edit; regenerated on every refresh. Intent lives in kendex.toml.";

/// One harness's rendering plus everything the user should hear about it.
#[derive(Debug)]
pub struct RenderedAgent {
    pub text: String,
    pub warnings: Vec<crate::render::RenderWarning>,
}

/// `Err` is a refusal: the harness cannot express the agent's permission
/// intent and rendering anyway would widen access. The caller surfaces the
/// reason and produces no artifact for that harness.
pub fn generate(agent: &EffectiveAgent) -> Result<RenderedAgent, String> {
    match agent.harness {
        HarnessId::Claude => Ok(claude::generate(agent)),
        HarnessId::Codex => Ok(codex::generate(agent)),
        HarnessId::Opencode => Ok(opencode::generate(agent)),
        HarnessId::Cursor => Ok(cursor::generate(agent)),
        HarnessId::Pi => pi::generate(agent),
        HarnessId::Gemini => Ok(gemini::generate(agent)),
        HarnessId::Copilot => Ok(copilot::generate(agent)),
    }
}

/// The filename a generated agent gets in the harness's native dir, under
/// the spelling that harness lists the agent by — an agent from a
/// plugin-registry catalog carries its plugin into the name.
pub fn file_name(harness: HarnessId, agent_name: &str) -> String {
    let agent_name = &crate::harness::rendered_name(harness, agent_name);
    match harness {
        HarnessId::Codex => format!("{agent_name}.toml"),
        HarnessId::Cursor => format!("{agent_name}.mdc"),
        // Copilot loads `<name>.agent.md`; the double extension is part of
        // what its loader looks for, not decoration (matrix §2).
        HarnessId::Copilot => format!("{agent_name}.agent.md"),
        _ => format!("{agent_name}.md"),
    }
}

/// Skills prose section for harnesses without a native skills field.
pub fn skills_prose(agent: &EffectiveAgent, skill_root_hint: &str) -> Option<String> {
    if agent.skills.is_empty() {
        return None;
    }
    let mut out = String::from("## Required Skills\n\nRead each before acting:\n");
    for skill in &agent.skills {
        out.push_str(&format!("- {skill}: {skill_root_hint}/{skill}/SKILL.md\n"));
    }
    Some(out)
}

/// Custom hooks rendered as prose, for every harness that does not run
/// hooks out of an agent's own file — which is all of them but Claude Code.
/// The matcher is said in this harness's own tool names: a hook written
/// against `Bash` means the same thing here, and printing Claude's word for
/// it in another harness's file asks the model to match on a name it has
/// never seen.
pub fn hooks_prose(agent: &EffectiveAgent) -> Option<String> {
    if agent.custom_hooks.is_empty() {
        return None;
    }
    let mut out = String::new();
    for hook in &agent.custom_hooks {
        let matcher = hook
            .matcher
            .as_deref()
            .map(|matcher| crate::render::vocab::hook_matcher(matcher, agent.harness).0)
            .unwrap_or_else(|| "every match".to_owned());
        out.push_str(&format!(
            "## Safety: {} on {}\n\n{}Run: `{}`\n\n",
            hook.event,
            matcher,
            hook.description
                .as_ref()
                .map(|d| format!("{d}\n\n"))
                .unwrap_or_default(),
            hook.command
        ));
    }
    Some(out.trim_end().to_owned())
}

pub fn kind() -> ItemKind {
    ItemKind::Agent
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn shared_instructions_render_first_inside_markers() {
        let mut table = BTreeMap::new();
        table.insert("all".to_owned(), "fleet rule".to_owned());
        table.insert("rust".to_owned(), "rust rule".to_owned());
        let merged = merged_instructions(&table, "rust").unwrap();
        assert!(merged.starts_with(SHARED_START));
        assert!(merged.contains("fleet rule"));
        assert!(merged.ends_with("rust rule"));
        let solo = merged_instructions(&table, "other").unwrap();
        assert!(solo.contains(SHARED_START) && !solo.contains("rust rule"));
    }

    #[test]
    fn deny_tools_merge_while_other_fields_prefer_project() {
        let source = FrontmatterOverrides {
            model: Some("sonnet".into()),
            deny_tools: Some(vec!["WebSearch".into()]),
            ..FrontmatterOverrides::default()
        };
        let project = FrontmatterOverrides {
            model: Some("opus".into()),
            deny_tools: Some(vec!["WebFetch".into(), "WebSearch".into()]),
            ..FrontmatterOverrides::default()
        };
        let merged = merge_overrides(Some(&source), Some(&project));
        assert_eq!(merged.model.as_deref(), Some("opus"));
        assert_eq!(
            merged.deny_tools,
            Some(vec!["WebSearch".into(), "WebFetch".into()])
        );
    }
}
