#!/usr/bin/env bash
# `toml-schema`: one red control per rejection clause.
#
# The silent failure it catches: `bot-instructions.toml` is hand-written and
# is the one input a person edits, so a misspelled key that the reader ignores
# leaves the default in force and the render is plausible, complete, and
# wrong.
#
# Every control here starts from a TOML with every `[bots]` flag false, which
# is a legitimate state that renders nothing, so each reds on its own mutation
# and not on a neighbour's.

. "$(dirname "$0")/lib/harness.sh"

repo="$(bi_minimal_repo toml-schema)"

# One control from a mutation appended to the minimal head.
c() { bi_control toml-schema "$1" "$repo"; }

# One control from a whole TOML written by the caller.
w() {
  local label
  label="$1"
  cat > "$repo/bot-instructions.toml"
  expect_red toml-schema "$label" check --repo "$repo"
}

# --- the shape set ----------------------------------------------------------
c 'an unknown table' <<'EOF'
[bot]
codex = true
EOF
c 'an unknown key in a known table' <<'EOF'
[exclusions]
derive_renders = true
EOF
c 'a value of the wrong type' <<'EOF'
[bots]
codex = "yes"
EOF
c 'an empty glob list' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "t"
globs = []
instructions = "x"
EOF
c 'an empty surface name' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = ""
globs = ["a/**"]
instructions = "x"
EOF
c 'a malformed surface name' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "Tests"
globs = ["a/**"]
instructions = "x"
EOF
c 'a duplicated surface name' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "t"
globs = ["a/**"]
instructions = "x"
[[surface]]
name = "t"
globs = ["b/**"]
instructions = "y"
EOF
c 'a reserved surface name' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "correctness"
globs = ["a/**"]
instructions = "x"
EOF
c 'an unknown doctrine block id' <<'EOF'
[doctrine.append]
no-such-block = "x"
EOF
w 'a schema value other than 1' <<'EOF'
schema = 2
[repo]
name = "fixture"
summary = "A fixture repository."
EOF

# The required-key clause derives from the Required column of
# `repo-toml.md` § Keys rather than restating which fields are required. An
# absent key is not an undefined one and has no value to be mistyped, so
# nothing in the shape set above reaches it.
w 'an absent required key stated in prose (schema)' <<'EOF'
[repo]
name = "fixture"
summary = "A fixture repository."
EOF
w 'an absent required key in a table row ([repo] name)' <<'EOF'
schema = 1
[repo]
summary = "A fixture repository."
EOF
w 'an absent required [repo] summary' <<'EOF'
schema = 1
[repo]
name = "fixture"
EOF
c 'an absent required [[exclusions.path]] reason' <<'EOF'
[[exclusions.path]]
glob = "a/**"
EOF
c 'an absent required [[surface]] instructions' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "t"
globs = ["a/**"]
EOF

# --- the content refusals ---------------------------------------------------
# The clauses are the cells of `repo-toml.md` § The content refusals; the
# predicates are that table's, encoded once in `scripts/lib/refusals.py`.
w 'a heading in [repo] summary, indented, which is the wide predicate' <<'EOF'
schema = 1
[repo]
name = "fixture"
summary = """
text
  ## forged
"""
EOF
w 'a frontmatter line in [repo] summary' <<'EOF'
schema = 1
[repo]
name = "fixture"
summary = """
text
---
more
"""
EOF
w 'the marker text in [repo] summary' <<'EOF'
schema = 1
[repo]
name = "fixture"
summary = "generated by bot-instructions is not a repo's to say"
EOF

# A control character arrives through TOML's own escapes: a summary written
# with a backslash-u-0001 escape parses cleanly and yields a literal byte, so
# the value is already decoded by the time the refusal sees it. Written as the
# escape rather than as a literal byte so this file stays readable.
printf 'schema = 1\n[repo]\nname = "fixture"\nsummary = "a\\u0001b"\n' \
  > "$repo/bot-instructions.toml"
expect_red toml-schema 'a control character in [repo] summary' check --repo "$repo"

w 'a space in [repo] name, outside its character class' <<'EOF'
schema = 1
[repo]
name = "fix ture"
summary = "A fixture repository."
EOF
w 'a space in [repo] tracker, outside its character class' <<'EOF'
schema = 1
[repo]
name = "fixture"
summary = "A fixture repository."
tracker = "KEN 1"
EOF
c 'comment-close in an exclusion reason' <<'EOF'
[[exclusions.path]]
glob = "a/**"
reason = "ends the comment --> and then some"
EOF
c 'a newline in an exclusion reason' <<'EOF'
[[exclusions.path]]
glob = "a/**"
reason = """
two
lines
"""
EOF
c 'non-ASCII in [tone] coderabbit' <<'EOF'
[tone]
coderabbit = "cafeé"
EOF
c 'a toml-delimiter in a [doctrine.replace] value' <<'EOF'
[doctrine.replace]
scope = "closes its own string \"\"\" then TOML"
EOF
c 'a heading in a [doctrine.append] value' <<'EOF'
[doctrine.append]
scope = """
text
# forged
"""
EOF
c 'the marker text in a [[surface]] instructions' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "t"
globs = ["a/**"]
instructions = "generated by bot-instructions"
EOF

# --- the glob dialect's path-shape clauses ----------------------------------
# The character class catches none of these: every byte in them is permitted,
# and an empty glob has no bytes at all.
g() {
  cat > "$repo/bot-instructions.toml" <<EOF
schema = 1
[repo]
name = "fixture"
summary = "A fixture repository."
[[exclusions.path]]
glob = "$2"
reason = "r"
EOF
  expect_red toml-schema "$1" check --repo "$repo"
}
g 'an empty glob' ''
g 'a leading slash' '/src/**'
g 'a trailing slash' 'src/'
g 'a .. component' '../**'
g 'an empty component' 'src//x'
g 'a brace, outside the class' '{a,b}/**'
g 'an extglob, outside the class' '@(a|b)/**'
g 'a comma, which Copilot applyTo splits on' 'a,b'
g 'a comment character, which .coderabbit.yaml reads as a comment' 'a#b'

c 'an exclusion glob declared twice' <<'EOF'
[[exclusions.path]]
glob = "a/**"
reason = "one"
[[exclusions.path]]
glob = "a/**"
reason = "two, and the second reason is the one a reader believes"
EOF

# --- the cross-flag set -----------------------------------------------------
c 'qodo_best_practices true with qodo false' <<'EOF'
[bots]
qodo_best_practices = true
EOF
c 'copilot true with codex false' <<'EOF'
[bots]
copilot = true
EOF
c 'surfaces with every route flag false' <<'EOF'
[bots]
codex = true
qodo = true
[[surface]]
name = "t"
globs = ["a/**"]
instructions = "x"
EOF
c 'a qodo_commands entry carrying an inline override' <<'EOF'
[cadence]
qodo_commands = ["/review --pr_reviewer.extra_instructions="]
EOF
c 'a qodo_commands entry outside the verb set' <<'EOF'
[cadence]
qodo_commands = ["/ask"]
EOF

# Every flag false is a legitimate state and passes: the clauses above are
# narrower than "renders nothing readable".
printf '%s' "$BI_MIN_HEAD" > "$repo/bot-instructions.toml"
expect_green 'every flag false passes and renders nothing' check --repo "$repo"
bi_run render --repo "$repo"
if printf '%s\n' "$bi_out" | grep -q 'nothing to render'; then
  ok 'render says it wrote nothing rather than exiting quietly'
else
  bad 'render says it wrote nothing rather than exiting quietly' "$bi_out"
fi

bi_summary
