#!/usr/bin/env bash
# `toml-schema`: one red control per rejection clause.
#
# The silent failure it catches: `bot-instructions.toml` is hand-written and
# is the one input a person edits, so a misspelled key that the reader ignores
# leaves the default in force and the render is plausible, complete, and
# wrong.
#
# Every control here starts from a TOML with every `[bots]` flag false, which
# is a legitimate state that renders nothing, so each reds on its own mutation
# and not on a neighbour's.

. "$(dirname "$0")/lib/harness.sh"

repo="$(bi_minimal_repo toml-schema)"

# One control from a mutation appended to the minimal head.
c() { bi_control toml-schema "$1" "$repo"; }

# One control from a whole TOML written by the caller.
w() {
  local label
  label="$1"
  cat > "$repo/bot-instructions.toml"
  expect_red toml-schema "$label" check --repo "$repo"
}

# --- the shape set ----------------------------------------------------------
c 'an unknown table' <<'EOF'
[bot]
codex = true
EOF
c 'an unknown key in a known table' <<'EOF'
[exclusions]
derive_renders = true
EOF
c 'a value of the wrong type' <<'EOF'
[bots]
codex = "yes"
EOF
c 'an empty glob list' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "t"
globs = []
instructions = "x"
EOF
c 'an empty surface name' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = ""
globs = ["a/**"]
instructions = "x"
EOF
c 'a malformed surface name' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "Tests"
globs = ["a/**"]
instructions = "x"
EOF
c 'a duplicated surface name' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "t"
globs = ["a/**"]
instructions = "x"
[[surface]]
name = "t"
globs = ["b/**"]
instructions = "y"
EOF
c 'a reserved surface name' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "correctness"
globs = ["a/**"]
instructions = "x"
EOF
c 'an unknown doctrine block id' <<'EOF'
[doctrine.append]
no-such-block = "x"
EOF
w 'a schema value other than 1' <<'EOF'
schema = 2
[repo]
name = "fixture"
summary = "A fixture repository."
EOF

# The required-key clause derives from the Required column of
# `repo-toml.md` § Keys rather than restating which fields are required. An
# absent key is not an undefined one and has no value to be mistyped, so
# nothing in the shape set above reaches it.
w 'an absent required key stated in prose (schema)' <<'EOF'
[repo]
name = "fixture"
summary = "A fixture repository."
EOF
w 'an absent required key in a table row ([repo] name)' <<'EOF'
schema = 1
[repo]
summary = "A fixture repository."
EOF
w 'an absent required [repo] summary' <<'EOF'
schema = 1
[repo]
name = "fixture"
EOF
c 'an absent required [[exclusions.path]] reason' <<'EOF'
[[exclusions.path]]
glob = "a/**"
EOF
c 'an absent required [[surface]] instructions' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "t"
globs = ["a/**"]
EOF

# --- the content refusals ---------------------------------------------------
# The clauses are the cells of `repo-toml.md` § The content refusals; the
# predicates are that table's, encoded once in `scripts/lib/refusals.py`.
w 'a heading in [repo] summary, indented, which is the wide predicate' <<'EOF'
schema = 1
[repo]
name = "fixture"
summary = """
text
  ## forged
"""
EOF
w 'a frontmatter line in [repo] summary' <<'EOF'
schema = 1
[repo]
name = "fixture"
summary = """
text
---
more
"""
EOF
w 'the marker text in [repo] summary' <<'EOF'
schema = 1
[repo]
name = "fixture"
summary = "generated by bot-instructions is not a repo's to say"
EOF

# A control character arrives through TOML's own escapes: a summary written
# with a backslash-u-0001 escape parses cleanly and yields a literal byte, so
# the value is already decoded by the time the refusal sees it. Written as the
# escape rather than as a literal byte so this file stays readable.
printf 'schema = 1\n[repo]\nname = "fixture"\nsummary = "a\\u0001b"\n' \
  > "$repo/bot-instructions.toml"
expect_red toml-schema 'a control character in [repo] summary' check --repo "$repo"

w 'a space in [repo] name, outside its character class' <<'EOF'
schema = 1
[repo]
name = "fix ture"
summary = "A fixture repository."
EOF
w 'a space in [repo] tracker, outside its character class' <<'EOF'
schema = 1
[repo]
name = "fixture"
summary = "A fixture repository."
tracker = "KEN 1"
EOF
c 'comment-close in an exclusion reason' <<'EOF'
[[exclusions.path]]
glob = "a/**"
reason = "ends the comment --> and then some"
EOF
c 'a newline in an exclusion reason' <<'EOF'
[[exclusions.path]]
glob = "a/**"
reason = """
two
lines
"""
EOF
c 'non-ASCII in [tone] coderabbit' <<'EOF'
[tone]
coderabbit = "cafeé"
EOF
c 'a toml-delimiter in a [doctrine.replace] value' <<'EOF'
[doctrine.replace]
scope = "closes its own string \"\"\" then TOML"
EOF
c 'a heading in a [doctrine.append] value' <<'EOF'
[doctrine.append]
scope = """
text
# forged
"""
EOF
c 'the marker text in a [[surface]] instructions' <<'EOF'
[bots]
codex = true
copilot = true
[[surface]]
name = "t"
globs = ["a/**"]
instructions = "generated by bot-instructions"
EOF

# --- the glob dialect's path-shape clauses ----------------------------------
# The character class catches none of these: every byte in them is permitted,
# and an empty glob has no bytes at all.
g() {
  cat > "$repo/bot-instructions.toml" <<EOF
schema = 1
[repo]
name = "fixture"
summary = "A fixture repository."
[[exclusions.path]]
glob = "$2"
reason = "r"
EOF
  expect_red toml-schema "$1" check --repo "$repo"
}
g 'an empty glob' ''
g 'a leading slash' '/src/**'
g 'a trailing slash' 'src/'
g 'a .. component' '../**'
g 'an empty component' 'src//x'
g 'a brace, outside the class' '{a,b}/**'
g 'an extglob, outside the class' '@(a|b)/**'
g 'a comma, which Copilot applyTo splits on' 'a,b'
g 'a comment character, which .coderabbit.yaml reads as a comment' 'a#b'

c 'an exclusion glob declared twice' <<'EOF'
[[exclusions.path]]
glob = "a/**"
reason = "one"
[[exclusions.path]]
glob = "a/**"
reason = "two, and the second reason is the one a reader believes"
EOF

# --- the cross-flag set -----------------------------------------------------
c 'qodo_best_practices true with qodo false' <<'EOF'
[bots]
qodo_best_practices = true
EOF
c 'copilot true with codex false' <<'EOF'
[bots]
copilot = true
EOF
c 'surfaces with every route flag false' <<'EOF'
[bots]
codex = true
qodo = true
[[surface]]
name = "t"
globs = ["a/**"]
instructions = "x"
EOF
c 'a qodo_commands entry carrying an inline override' <<'EOF'
[cadence]
qodo_commands = ["/review --pr_reviewer.extra_instructions="]
EOF
c 'a qodo_commands entry outside the verb set' <<'EOF'
[cadence]
qodo_commands = ["/ask"]
EOF

# Every flag false is a legitimate state and passes: the clauses above are
# narrower than "renders nothing readable".
printf '%s' "$BI_MIN_HEAD" > "$repo/bot-instructions.toml"
expect_green 'every flag false passes and renders nothing' check --repo "$repo"
bi_run render --repo "$repo"
if printf '%s\n' "$bi_out" | grep -q 'nothing to render'; then
  ok 'render says it wrote nothing rather than exiting quietly'
else
  bad 'render says it wrote nothing rather than exiting quietly' "$bi_out"
fi

# A surface whose text is empty renders a `path_instructions` entry with no
# text, a `.instructions.md` with a marker and nothing under it, and a
# best-practices section with no body. `macroscope-render`'s no-text clause is
# the only thing that would have caught it, and it does not run with
# `[bots] macroscope` false — which is a legitimate flag state.
repo="$(bi_new_repo empty-surface)"
python3 - "$repo" "$BI_FIXTURES/canonical.toml" <<'PY'
import re, sys
repo, src = sys.argv[1], sys.argv[2]
# The canonical TOML with one surface's text emptied and nothing else changed,
# so the clause under test is the only one with anything to say. A fixture
# with every route flag false reds `toml-schema` on its own.
text = re.sub(r'(name = "tests".*?instructions = """\n).*?(\n""")', r'\1\2',
              open(src).read(), flags=re.S)
open(repo + "/bot-instructions.toml", "w").write(text)
PY
expect_red toml-schema 'a [[surface]] whose instructions are empty' \
  render --dry-run --repo "$repo"

# The dialect's class permits `[`, `]` and every byte between them, so a
# reversed range is made of nothing but allowed characters and is a pattern no
# engine compiles. Proving it compiles is a `toml-schema` clause, which is what
# makes it a finding rather than a traceback out of the dead-exclusion clause.
repo="$(bi_minimal_repo reversed-class)"
bi_control toml-schema 'a reversed character range, which is in the class and compiles nowhere' "$repo" <<'EOF'

[[exclusions.path]]
glob = "src/[z-a].rs"
reason = "a range no engine reads"
EOF

# The same clause names WHICH key it read, like every other clause in
# `globs.check`. A message that only quotes the pattern leaves an operator
# with several surfaces and several globs nothing to grep, and the glob it
# quotes is the one the author wrote rather than the collapsed form `re` saw:
# `**/**/` becomes `**/` before the compile, and quoting that names a string
# no file in the repo holds.
expect_finding() {
  local want carries label
  want="$1"; carries="$2"; label="$3"; shift 3
  bi_run "$@"
  if [ "$bi_status" -eq 0 ]; then
    bad "$label" "expected $want to red; the run passed"
  elif ! printf '%s\n' "$bi_out" | grep -q "^$want:"; then
    bad "$label" "expected '$want:'; got: $(printf '%s' "$bi_out" | head -1)"
  elif printf '%s\n' "$bi_out" | grep -qF -- "$carries"; then
    ok "$label"
  else
    bad "$label" "expected the finding to carry '$carries'; got: $(printf '%s' "$bi_out" | head -1)"
  fi
}

repo="$(bi_minimal_repo reversed-class-surface)"
{ printf '%s' "$BI_MIN_HEAD"; cat <<'EOF'
[[surface]]
name = "tests"
globs = ["src/**/**/[z-a].rs"]
reviewer_only = true
instructions = """
A surface whose glob compiles nowhere.
"""
EOF
} > "$repo/bot-instructions.toml"
expect_finding toml-schema '[[surface]][0] globs[0]:' \
  'a surface glob that compiles nowhere names the key it came from' \
  check --repo "$repo"
expect_finding toml-schema "glob 'src/**/**/[z-a].rs'" \
  'and quotes the glob as written, not the collapsed pattern' \
  check --repo "$repo"

# The derived side: a manifest row is the one glob source no author wrote as a
# glob, and the refusal has to name the row that produced it.
repo="$(bi_new_repo reversed-class-derived)"
mkdir -p "$repo/.agents/skills/zw"
printf 'x\n' > "$repo/.agents/skills/zw/SKILL.md"
printf '\n[skills."z[y-a]w"]\nsource = "."\nenabled = true\n' >> "$repo/kendex.toml"
git -C "$repo" add -A >/dev/null 2>&1
expect_finding exclusion-consistency '[skills.z[y-a]w]' \
  'a derived glob that compiles nowhere names the manifest row' \
  check --repo "$repo"

# § Cross-file sets: the content-refusal table is the single statement, and
# three structures encode it. Held against them here, so a row or a marked
# cell added on one side without the other reds rather than being noticed by a
# reader who happens to count.
if python3 - "$BI_ROOT/skills/bot-instructions" <<'PROBE'; then
import os, re, sys
PKG = sys.argv[1]
sys.path.insert(0, os.path.join(PKG, "scripts"))
from lib import refusals
from lib.constants import QODO_VERBS

table = open(os.path.join(PKG, "schemas/repo-toml.md")).read()
rows = [ln for ln in table.split("\n")
        if ln.startswith("| ") and ln.count("|") == 10
        and not ln.startswith("| Input string")
        and not ln.startswith("|---")]
if len(rows) != 10:
    sys.exit(f"read {len(rows)} rows out of the table, expected the documented ten")

# The six columns whose cells are a yes/dash, in the table's order, against
# the predicate names ROWS spells.
COLUMNS = ["heading", "frontmatter", "marker", "comment-close", "toml-delimiter", "control"]
# The table's row labels, mapped to the ROWS key or to the structure that owns
# them. Two rows are not content classes and are enforced elsewhere.
ELSEWHERE = {
    "`[[surface]] globs`, `exclude_globs`, `[[exclusions.path]] glob`": "globs.check",
    "`[cadence] qodo_commands` entries": "config._cadence",
}
LABELS = {
    "`[repo] name`": "[repo] name",
    "`[repo] tracker`": "[repo] tracker",
    "`[repo] summary`": "[repo] summary",
    "`[[surface]] instructions`": "[[surface]] instructions",
    "`[doctrine.append]` / `[doctrine.replace]` values": "[doctrine.*] values",
    "doctrine block text": "doctrine block text",
    "`[[exclusions.path]] reason`": "[[exclusions.path]] reason",
    "`[tone] coderabbit`": "[tone] coderabbit",
}
seen = set()
for line in rows:
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    label = cells[0]
    if label in ELSEWHERE:
        seen.add(label)
        continue
    if label not in LABELS:
        sys.exit(f"table row {label!r} is neither a ROWS row nor one of the two "
                 "the table says are enforced elsewhere")
    key = LABELS[label]
    if key not in refusals.ROWS:
        sys.exit(f"table row {label!r} has no {key!r} in refusals.ROWS")
    seen.add(label)
    want = {COLUMNS[i] for i, cell in enumerate(cells[1:7]) if cell == "yes"}
    have = {p for p in refusals.ROWS[key][0] if p in COLUMNS}
    if want != have:
        sys.exit(f"{key!r}: the table marks {sorted(want)} and ROWS runs {sorted(have)}")
    enforced = cells[8]
    owner = refusals.ROWS[key][1]
    if owner not in enforced:
        sys.exit(f"{key!r}: the table's Enforced column says {enforced!r}, ROWS says {owner!r}")
if len(seen) != 10:
    sys.exit(f"matched {len(seen)} of the table's rows")
if set(LABELS.values()) != set(refusals.ROWS):
    sys.exit("refusals.ROWS holds a row the table does not")
# The two the table says live elsewhere, held against the structures that own
# them rather than taken on trust.
from lib import globs
from lib.errors import InputError
try:
    globs.check("a,b", "control")
except InputError:
    pass
else:
    sys.exit("globs.check does not enforce the glob row")
# The verb row of that table has its own table one section up, and its Role
# column is what `qodo-parity`'s guard reads. Compared cell by cell rather
# than counted: `if not QODO_VERBS` passes for ANY role assignment, so a role
# flipped on one side agreed with nothing.
verbs = {}
for ln in table.split("\n"):
    cells = [c.strip().strip("`") for c in ln.strip().strip("|").split("|")]
    if len(cells) == 3 and cells[0].startswith("/"):
        verbs[cells[0]] = cells[2]
if verbs != QODO_VERBS:
    sys.exit(f"[cadence] verb table says {verbs}; constants.QODO_VERBS says {QODO_VERBS}")
PROBE
  ok 'the content-refusal table agrees with the three structures that encode it'
else
  bad 'the content-refusal table agrees with the three structures that encode it'
fi

# The same class holds three characters ABOVE the C0 range, because a YAML
# reader breaks a line on all three: U+0085 NEL, U+2028 LINE SEPARATOR and
# U+2029 PARAGRAPH SEPARATOR. A `reason` carrying one is emitted into
# `.coderabbit.yaml` as the comment line above its entry, and PyYAML then reads
# the rest of it as a `path_filters:` key of its own whose first entry has no
# `!` — the state `renders.md` names as the one that turns the exclusion list
# into an allowlist. Each is paired with the ordinary value it deviates from by
# that one character, so the control cannot pass by rejecting everything.
#
# Written as TOML escapes, like the C0 case above: a literal separator in this
# file would be invisible to a reader and to a diff.
repo="$(bi_minimal_repo line-separators)"
mkdir -p "$repo/a"
printf 'x\n' > "$repo/a/f.rs"
git -C "$repo" add -A >/dev/null 2>&1

bi_reason() {
  { printf '%s' "$BI_MIN_HEAD"
    printf '[exclusions]\n[[exclusions.path]]\nglob = "a/**"\nreason = "a generated%s tree"\n' "$1"
  } > "$repo/bot-instructions.toml"
}
for cp in u0085 u2028 u2029; do
  bi_reason ''
  expect_green "an ordinary [[exclusions.path]] reason, the pair for \\$cp" \
    check --repo "$repo"
  bi_reason "\\$cp"
  expect_red toml-schema "a line separator \\$cp in [[exclusions.path]] reason" \
    check --repo "$repo"
done

# The same character in `[[surface]] instructions`, which reaches
# `.coderabbit.yaml` inside a block scalar: the text after it would be emitted
# unindented, end the scalar, and leave PyYAML unable to read the file at all.
bi_surface() {
  { printf '%s' "$BI_MIN_HEAD"
    # A surface needs a route for its text, or `toml-schema` reds on the
    # surface set instead and the pair proves nothing about the separator.
    printf '[bots]\ncodex = true\ncopilot = true\n'
    printf '[[surface]]\nname = "tests"\nglobs = ["a/**"]\nreviewer_only = true\n'
    printf 'instructions = "An ordinary%s surface."\n' "$1"
  } > "$repo/bot-instructions.toml"
}
# `render --dry-run`, like the empty-instructions control above: this pair
# needs a bot enabled for the surface text to have a route, and a fixture with
# bots on and no rendered outputs reds on `drift` under `check`.
bi_surface ''
expect_green 'an ordinary [[surface]] instructions, the pair below' \
  render --dry-run --repo "$repo"
bi_surface '\u2028'
expect_red toml-schema 'a line separator in [[surface]] instructions' \
  render --dry-run --repo "$repo"

bi_summary
