// Generated by pi-extensions/pi-root-policy.mjs; do not edit.
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, posix, resolve, win32 } from "node:path";

export const PI_PROJECT_MARKERS=[".pi",".git",".kendex-lock.json"];

export function piGlobalRoot(value=process.env.PI_CODING_AGENT_DIR, home=homedir(), platform=process.platform === "win32" ? "win32" : "posix") {
	const p=platform === "win32" ? win32 : posix, raw=value?.trim(), path=raw === "~" ? home : raw?.startsWith("~/") ? p.join(home, raw.slice(2)) : raw, absolute=platform === "win32" ? (/^[A-Za-z]:[\\/]/.test(path ?? "") || /^(?:\\\\|\/\/)[^\\/]+[\\/][^\\/]+(?:[\\/]|$)/.test(path ?? "")) : path?.startsWith("/");
	return absolute ? p.resolve(path) : p.resolve(home, ".pi", "agent");
}

export function piProjectRoot(cwd, markers=PI_PROJECT_MARKERS, home=homedir()) {
	const start=resolve(cwd), stop=resolve(home);
	if (start === stop) return undefined;
	let current=start;
	while (current !== stop) {
		if (markers.some((marker) => existsSync(join(current, marker)))) return current;
		const parent=dirname(current);
		if (parent === current) break;
		current=parent;
	}
	return start;
}
